-- Add Securities Notice workflow columns to MY_NOTICES.
-- Status values: DRAFT, PENDING_APPROVAL, RETURNED_FOR_REVISION,
-- SENT_AWAITING_RESPONSE, SUBPOENA_RECEIVED_PENDING_REVIEW, RECORDS_RELEASED.

IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'TEMPLATE_FORM_ID') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [TEMPLATE_FORM_ID] INT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'NOTICE_STATUS') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [NOTICE_STATUS] NVARCHAR(40) NOT NULL DEFAULT 'DRAFT';
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'SUBMITTED_BY') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [SUBMITTED_BY] INT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'SUBMITTED_AT') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [SUBMITTED_AT] DATETIME2 NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'APPROVED_BY') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [APPROVED_BY] INT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'APPROVED_AT') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [APPROVED_AT] DATETIME2 NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'REJECTED_BY') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [REJECTED_BY] INT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'REJECTED_AT') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [REJECTED_AT] DATETIME2 NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'REJECTION_REASON') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [REJECTION_REASON] NVARCHAR(2000) NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'SENT_AT') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [SENT_AT] DATETIME2 NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'DISCLAIMER_STATE') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [DISCLAIMER_STATE] BIT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'FIRST_TIME_RECIPIENT_FLAG') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [FIRST_TIME_RECIPIENT_FLAG] BIT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'SUBPOENA_RIDER_ID') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [SUBPOENA_RIDER_ID] INT NULL;
IF COL_LENGTH('GUARDIAN.MY_NOTICES', 'ATTACHED_SUBPOENA_ATTACHMENT_ID') IS NULL
    ALTER TABLE [GUARDIAN].[MY_NOTICES] ADD [ATTACHED_SUBPOENA_ATTACHMENT_ID] INT NULL;

-- FK to FORMS template
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MY_NOTICES_TEMPLATE_FORM')
    ALTER TABLE [GUARDIAN].[MY_NOTICES]
    ADD CONSTRAINT [FK_MY_NOTICES_TEMPLATE_FORM] FOREIGN KEY ([TEMPLATE_FORM_ID])
        REFERENCES [GUARDIAN].[FORMS] ([FORM_ID]);

-- Backfill NOTICE_STATUS from BUTTON_STATUS where unset
UPDATE [GUARDIAN].[MY_NOTICES]
SET NOTICE_STATUS = CASE
    WHEN BUTTON_STATUS IN ('DRAFT', 'draft') THEN 'DRAFT'
    WHEN BUTTON_STATUS IN ('SENT', 'PUBLISHED', 'published') THEN 'SENT_AWAITING_RESPONSE'
    ELSE 'DRAFT'
END
WHERE NOTICE_STATUS = 'DRAFT' AND BUTTON_STATUS IS NOT NULL;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MY_NOTICES_NOTICE_STATUS')
    CREATE INDEX [IX_MY_NOTICES_NOTICE_STATUS] ON [GUARDIAN].[MY_NOTICES] ([NOTICE_STATUS]);
