IF COL_LENGTH('GUARDIAN.FORMS', 'NOTICE_SUBTYPE') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS] ADD [NOTICE_SUBTYPE] NVARCHAR(40) NULL;
    -- Values: SECURITIES_FRAUD, SUBPOENA_RIDER (NULL for non-notice templates)
IF COL_LENGTH('GUARDIAN.FORMS', 'FRAUD_TYPE') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS] ADD [FRAUD_TYPE] NVARCHAR(40) NULL;
    -- Values: SECURITIES_MANIPULATION, ATO, CHECK_FRAUD, WIRE_FRAUD
IF COL_LENGTH('GUARDIAN.FORMS', 'REQUIRES_MANAGER_APPROVAL') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS] ADD [REQUIRES_MANAGER_APPROVAL] BIT NOT NULL DEFAULT 0;
IF COL_LENGTH('GUARDIAN.FORMS', 'COMPLIANCE_DISCLAIMER_ENABLED') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS] ADD [COMPLIANCE_DISCLAIMER_ENABLED] BIT NOT NULL DEFAULT 0;
IF COL_LENGTH('GUARDIAN.FORMS', 'TITLE_FORMAT') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS] ADD [TITLE_FORMAT] NVARCHAR(255) NULL;
    -- e.g. "[SECURITY_SYMBOL] — $[LOSS_EXPOSURE]"

-- Per-template field flags live on the FIELDS-to-FORM linkage. Add to FORMS_FIELDS.
IF COL_LENGTH('GUARDIAN.FORMS_FIELDS', 'IS_PII') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS_FIELDS] ADD [IS_PII] BIT NOT NULL DEFAULT 0;
IF COL_LENGTH('GUARDIAN.FORMS_FIELDS', 'IS_ENABLED') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS_FIELDS] ADD [IS_ENABLED] BIT NOT NULL DEFAULT 1;
IF COL_LENGTH('GUARDIAN.FORMS_FIELDS', 'IS_LOCKED_BY_JAFAR') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS_FIELDS] ADD [IS_LOCKED_BY_JAFAR] BIT NOT NULL DEFAULT 0;
IF COL_LENGTH('GUARDIAN.FORMS_FIELDS', 'IS_READ_ONLY') IS NULL
    ALTER TABLE [GUARDIAN].[FORMS_FIELDS] ADD [IS_READ_ONLY] BIT NOT NULL DEFAULT 0;
