IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'RECIPIENT_VERIFICATIONS' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[RECIPIENT_VERIFICATIONS] (
        [VERIFICATION_ID] INT IDENTITY(1,1) NOT NULL,
        [RECIPIENT_USER_ID] INT NOT NULL,
        [COMPANY_ID]        INT NOT NULL,
        [VERIFIED_STATUS]   NVARCHAR(32) NOT NULL DEFAULT 'FIRST_TIME',
        [VERIFIED_AT]       DATETIME2 NULL,
        [FIRST_NOTICE_ID]   INT NULL,
        CONSTRAINT [PK_RECIPIENT_VERIFICATIONS] PRIMARY KEY CLUSTERED ([VERIFICATION_ID]),
        CONSTRAINT [UQ_RECIPIENT_VERIFICATIONS_USER_COMPANY] UNIQUE ([RECIPIENT_USER_ID], [COMPANY_ID]),
        CONSTRAINT [FK_RV_USER] FOREIGN KEY ([RECIPIENT_USER_ID]) REFERENCES [GUARDIAN].[USERS] ([USER_ID]),
        CONSTRAINT [FK_RV_FIRST_NOTICE] FOREIGN KEY ([FIRST_NOTICE_ID]) REFERENCES [GUARDIAN].[MY_NOTICES] ([NOTICE_ID])
    );
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_RV_STATUS')
    CREATE INDEX [IX_RV_STATUS] ON [GUARDIAN].[RECIPIENT_VERIFICATIONS] ([COMPANY_ID], [VERIFIED_STATUS]);
