IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SUBPOENA_RIDERS' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[SUBPOENA_RIDERS] (
        [RIDER_ID]            INT IDENTITY(1,1) NOT NULL,
        [LANGUAGE_TEMPLATE_ID] INT NOT NULL,
        [FRAUD_TYPE]          NVARCHAR(40) NOT NULL,
        [POPULATED_LANGUAGE]  NVARCHAR(MAX) NOT NULL,
        [TOKEN_VALUES_JSON]   NVARCHAR(MAX) NOT NULL, -- {"SECURITY_SYMBOL":"AAPL",...}
        [INCIDENT_NOTICE_ID]  INT NULL,
        [CREATED_BY]          INT NOT NULL,
        [COMPANY_ID]          INT NOT NULL,
        [CREATED_AT]          DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_SUBPOENA_RIDERS] PRIMARY KEY CLUSTERED ([RIDER_ID]),
        CONSTRAINT [FK_SR_NOTICE] FOREIGN KEY ([INCIDENT_NOTICE_ID]) REFERENCES [GUARDIAN].[MY_NOTICES] ([NOTICE_ID])
    );
END
