IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SUBPOENA_LANGUAGE_TEMPLATES' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[SUBPOENA_LANGUAGE_TEMPLATES] (
        [LANGUAGE_TEMPLATE_ID] INT IDENTITY(1,1) NOT NULL,
        [FRAUD_TYPE]           NVARCHAR(40) NOT NULL,
        [BASE_LANGUAGE]        NVARCHAR(MAX) NOT NULL,
        [TOKENS_JSON]          NVARCHAR(MAX) NOT NULL,
            -- [{token:"[SECURITY_SYMBOL]",description:"...",autoPopulateFromIncident:true},...]
        [CREATED_BY]           INT NOT NULL,
        [COMPANY_ID]           INT NOT NULL,
        [CREATED_AT]           DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [UPDATED_AT]           DATETIME2 NULL,
        CONSTRAINT [PK_SUBPOENA_LANG_TEMPLATES] PRIMARY KEY CLUSTERED ([LANGUAGE_TEMPLATE_ID]),
        CONSTRAINT [UQ_SUBPOENA_LANG_FRAUD_PER_COMPANY] UNIQUE ([COMPANY_ID], [FRAUD_TYPE])
    );
END
