-- External users (law enforcement) are full USERS rows with ROLE_ID=5 already.
-- Add an assignment table linking external users to specific notices.
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXTERNAL_NOTICE_ASSIGNMENTS' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[EXTERNAL_NOTICE_ASSIGNMENTS] (
        [ASSIGNMENT_ID]      INT IDENTITY(1,1) NOT NULL,
        [NOTICE_ID]          INT NOT NULL,
        [EXTERNAL_USER_ID]   INT NOT NULL,
        [COMPANY_ID]         INT NOT NULL,
        [AGENCY_NAME]        NVARCHAR(255) NULL,
        [CREATED_AT]         DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_EXTERNAL_NOTICE_ASSIGNMENTS] PRIMARY KEY CLUSTERED ([ASSIGNMENT_ID]),
        CONSTRAINT [UQ_ENA_NOTICE_USER] UNIQUE ([NOTICE_ID], [EXTERNAL_USER_ID]),
        CONSTRAINT [FK_ENA_NOTICE] FOREIGN KEY ([NOTICE_ID]) REFERENCES [GUARDIAN].[MY_NOTICES] ([NOTICE_ID]),
        CONSTRAINT [FK_ENA_USER] FOREIGN KEY ([EXTERNAL_USER_ID]) REFERENCES [GUARDIAN].[USERS] ([USER_ID])
    );
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ENA_COMPANY_EXTERNAL_USER')
    CREATE INDEX [IX_ENA_COMPANY_EXTERNAL_USER] ON [GUARDIAN].[EXTERNAL_NOTICE_ASSIGNMENTS] ([COMPANY_ID], [EXTERNAL_USER_ID]);

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXTERNAL_CALL_REQUESTS' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[EXTERNAL_CALL_REQUESTS] (
        [CALL_REQUEST_ID]   INT IDENTITY(1,1) NOT NULL,
        [NOTICE_ID]         INT NOT NULL,
        [EXTERNAL_USER_ID]  INT NOT NULL,
        [PROPOSED_TIMES]    NVARCHAR(MAX) NOT NULL, -- JSON array of ISO timestamps
        [MEETING_LINK]      NVARCHAR(1024) NULL,    -- filled by Processor reply
        [CREATED_AT]        DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_EXTERNAL_CALL_REQUESTS] PRIMARY KEY CLUSTERED ([CALL_REQUEST_ID]),
        CONSTRAINT [FK_ECR_NOTICE] FOREIGN KEY ([NOTICE_ID]) REFERENCES [GUARDIAN].[MY_NOTICES] ([NOTICE_ID]),
        CONSTRAINT [FK_ECR_USER]   FOREIGN KEY ([EXTERNAL_USER_ID]) REFERENCES [GUARDIAN].[USERS] ([USER_ID])
    );
END
