-- Conditional migration - only add columns if they don't exist
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'GUARDIAN' 
               AND TABLE_NAME = 'WORK_PROGRESS' 
               AND COLUMN_NAME = 'IS_SYSTEM_GENERATED')
BEGIN
    PRINT 'Adding IS_SYSTEM_GENERATED column...'
    ALTER TABLE GUARDIAN.WORK_PROGRESS ADD IS_SYSTEM_GENERATED BIT DEFAULT 0 NOT NULL;
END
ELSE
    PRINT 'IS_SYSTEM_GENERATED column already exists'

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'GUARDIAN' 
               AND TABLE_NAME = 'WORK_PROGRESS' 
               AND COLUMN_NAME = 'RELATED_TASK_ID')
BEGIN
    PRINT 'Adding RELATED_TASK_ID column...'
    ALTER TABLE GUARDIAN.WORK_PROGRESS ADD RELATED_TASK_ID INT NULL;
END
ELSE
    PRINT 'RELATED_TASK_ID column already exists'

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'GUARDIAN' 
               AND TABLE_NAME = 'WORK_PROGRESS' 
               AND COLUMN_NAME = 'STATUS_FROM')
BEGIN
    PRINT 'Adding STATUS_FROM column...'
    ALTER TABLE GUARDIAN.WORK_PROGRESS ADD STATUS_FROM VARCHAR(50) NULL;
END
ELSE
    PRINT 'STATUS_FROM column already exists'

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'GUARDIAN' 
               AND TABLE_NAME = 'WORK_PROGRESS' 
               AND COLUMN_NAME = 'STATUS_TO')
BEGIN
    PRINT 'Adding STATUS_TO column...'
    ALTER TABLE GUARDIAN.WORK_PROGRESS ADD STATUS_TO VARCHAR(50) NULL;
END
ELSE
    PRINT 'STATUS_TO column already exists'

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = 'GUARDIAN' 
               AND TABLE_NAME = 'WORK_PROGRESS' 
               AND COLUMN_NAME = 'EVENT_DATA')
BEGIN
    PRINT 'Adding EVENT_DATA column...'
    ALTER TABLE GUARDIAN.WORK_PROGRESS ADD EVENT_DATA VARCHAR(4000) NULL;
END
ELSE
    PRINT 'EVENT_DATA column already exists'

PRINT 'Milestone tracking schema check completed!';