-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- [GUARDIAN-DEV].dbo.ATTACHMENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.ATTACHMENTS;

CREATE TABLE [GUARDIAN-DEV].dbo.ATTACHMENTS (
	ATTACHMENT_ID int IDENTITY(1,1) NOT NULL,
	REQUEST_ID int NOT NULL,
	FILE_NAME varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ATTACHMENT varbinary(MAX) NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_ATTACHMENTS PRIMARY KEY (ATTACHMENT_ID)
);


-- [GUARDIAN-DEV].dbo.COMPANY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.COMPANY;

CREATE TABLE [GUARDIAN-DEV].dbo.COMPANY (
	COMPANY_ID int IDENTITY(1,1) NOT NULL,
	NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ADDRESS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PHONE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATED_AT datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK__COMPANY__73B8DCFF3D624EE3 PRIMARY KEY (COMPANY_ID)
);


-- [GUARDIAN-DEV].dbo.FIELDS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FIELDS;

CREATE TABLE [GUARDIAN-DEV].dbo.FIELDS (
	FIELD_ID int IDENTITY(1,1) NOT NULL,
	FIELD_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FIELD_TYPE_ID int NOT NULL,
	DISPLAY_FORMAT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HAS_LOOKUP bit DEFAULT 0 NOT NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	IS_ACTIVE bit DEFAULT 0 NOT NULL,
	IS_DELETED bit DEFAULT 0 NOT NULL,
	IS_REQUIRED bit DEFAULT 0 NOT NULL,
	IS_SENSITIVE bit DEFAULT 0 NOT NULL,
	CAN_SELECT_MULIPLE bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	SysStartTime datetime2 DEFAULT sysutcdatetime() NOT NULL,
	SysEndTime datetime2 DEFAULT CONVERT([datetime2],'9999-12-31 23:59:59.9999999') NOT NULL,
	FIELD_LOOKUP_DISPLAY_TYPE_ID int NULL,
	ORGANIZATION_ID int NULL,
	CONSTRAINT PK_FIELD PRIMARY KEY (FIELD_ID)
);


-- [GUARDIAN-DEV].dbo.FIELDS_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FIELDS_HISTORY;

CREATE TABLE [GUARDIAN-DEV].dbo.FIELDS_HISTORY (
	FIELD_ID int NOT NULL,
	FIELD_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FIELD_TYPE_ID int NOT NULL,
	DISPLAY_FORMAT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HAS_LOOKUP bit NOT NULL,
	IS_PUBLIC bit NOT NULL,
	IS_ACTIVE bit NOT NULL,
	IS_DELETED bit NOT NULL,
	IS_REQUIRED bit NOT NULL,
	IS_SENSITIVE bit NOT NULL,
	CAN_SELECT_MULIPLE bit NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL,
	FIELD_LOOKUP_DISPLAY_TYPE_ID int NULL,
	ORGANIZATION_ID int NULL
);
 CREATE CLUSTERED INDEX ix_FIELDS_HISTORY ON GUARDIAN-DEV.dbo.FIELDS_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].dbo.FIELDS_LOOKUP definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FIELDS_LOOKUP;

CREATE TABLE [GUARDIAN-DEV].dbo.FIELDS_LOOKUP (
	FIELD_LOOKUP_ID int IDENTITY(1,1) NOT NULL,
	FIELD_ID int NOT NULL,
	LOOKUP_CODE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LOOKUP_DESCRIPTION varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_FIELDS_LOOKUP PRIMARY KEY (FIELD_LOOKUP_ID)
);


-- [GUARDIAN-DEV].dbo.FIELD_LOOKUP_DISPLAY_TYPE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FIELD_LOOKUP_DISPLAY_TYPE;

CREATE TABLE [GUARDIAN-DEV].dbo.FIELD_LOOKUP_DISPLAY_TYPE (
	FIELD_LOOKUP_DISPLAY_TYPE_ID int IDENTITY(1,1) NOT NULL,
	FIELD_LOOKUP_DISPLAY_TYPE_DESCRIPTION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	CONSTRAINT PK_FIELD_LOOKUP_DISPLAY_TYPE PRIMARY KEY (FIELD_LOOKUP_DISPLAY_TYPE_ID)
);


-- [GUARDIAN-DEV].dbo.FIELD_TYPE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FIELD_TYPE;

CREATE TABLE [GUARDIAN-DEV].dbo.FIELD_TYPE (
	FIELD_TYPE_ID int IDENTITY(1,1) NOT NULL,
	FIELD_TYPE_DESC varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	CONSTRAINT PK_FIELD_TYPE PRIMARY KEY (FIELD_TYPE_ID)
);


-- [GUARDIAN-DEV].dbo.FORMS_FIELDS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_FIELDS;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_FIELDS (
	FORM_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	IS_REQUIRED bit DEFAULT 0 NOT NULL,
	SORT_ORDER int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL
);


-- [GUARDIAN-DEV].dbo.FORMS_GROUPS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_GROUPS;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_GROUPS (
	GROUP_ID int IDENTITY(1,1) NOT NULL,
	ORGANIZATION_ID int NULL,
	GROUP_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GROUP_DESCRIPTION varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_GROUP PRIMARY KEY (GROUP_ID)
);


-- [GUARDIAN-DEV].dbo.FORMS_GROUPS_FIELDS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_GROUPS_FIELDS;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_GROUPS_FIELDS (
	GROUP_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	SORT_ORDER int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL
);


-- [GUARDIAN-DEV].dbo.FORMS_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_HISTORY;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_HISTORY (
	FORM_ID int NOT NULL,
	FORM_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FORM_DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ORGANIZATION_ID int NULL,
	IS_PUBLIC bit NOT NULL,
	IS_ACTIVE bit NOT NULL,
	IS_DELETED bit NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL,
	COMPANY_ID int NULL
);
 CREATE CLUSTERED INDEX ix_FORMS_HISTORY ON GUARDIAN-DEV.dbo.FORMS_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].dbo.FORMS_INSTANCE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE (
	FORM_INSTANCE_ID int IDENTITY(1,1) NOT NULL,
	FORM_ID int NOT NULL,
	ASSIGNED_ID int NOT NULL,
	SUBMITTED_DATE datetime NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	SysStartTime datetime2 DEFAULT sysutcdatetime() NOT NULL,
	SysEndTime datetime2 DEFAULT CONVERT([datetime2],'9999-12-31 23:59:59.9999999') NOT NULL,
	CONSTRAINT PK_FORMS_INSTANCE PRIMARY KEY (FORM_INSTANCE_ID)
);


-- [GUARDIAN-DEV].dbo.FORMS_INSTANCE_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE_HISTORY;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE_HISTORY (
	FORM_INSTANCE_ID int NOT NULL,
	FORM_ID int NOT NULL,
	ASSIGNED_ID int NOT NULL,
	SUBMITTED_DATE datetime NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL
);
 CREATE CLUSTERED INDEX ix_FORMS_INSTANCE_HISTORY ON GUARDIAN-DEV.dbo.FORMS_INSTANCE_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].dbo.FORMS_INSTANCE_VALUES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE_VALUES;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE_VALUES (
	FORM_INSTANCE_VALUE_ID int IDENTITY(1,1) NOT NULL,
	FORM_INSTANCE_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	VALUE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	SysStartTime datetime2 DEFAULT sysutcdatetime() NOT NULL,
	SysEndTime datetime2 DEFAULT CONVERT([datetime2],'9999-12-31 23:59:59.9999999') NOT NULL,
	CONSTRAINT PK_FORMS_INSTANCE_VALUES PRIMARY KEY (FORM_INSTANCE_VALUE_ID)
);


-- [GUARDIAN-DEV].dbo.FORMS_INSTANCE_VALUES_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE_VALUES_HISTORY;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS_INSTANCE_VALUES_HISTORY (
	FORM_INSTANCE_VALUE_ID int NOT NULL,
	FORM_INSTANCE_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	VALUE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL
);
 CREATE CLUSTERED INDEX ix_FORMS_INSTANCE_VALUES_HISTORY ON GUARDIAN-DEV.dbo.FORMS_INSTANCE_VALUES_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].dbo.INVITES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.INVITES;

CREATE TABLE [GUARDIAN-DEV].dbo.INVITES (
	INVITE_ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLE_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	TOKEN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXPIRES_AT datetime2 NOT NULL,
	USED_AT datetime2 NULL,
	CREATED_AT datetime2 DEFAULT sysdatetime() NOT NULL,
	CONSTRAINT PK__INVITES__F55A91112E684DE5 PRIMARY KEY (INVITE_ID),
	CONSTRAINT UQ__INVITES__05BE64EDCB9633D7 UNIQUE (TOKEN)
);


-- [GUARDIAN-DEV].dbo.MILESTONES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.MILESTONES;

CREATE TABLE [GUARDIAN-DEV].dbo.MILESTONES (
	MILESTONE_ID int IDENTITY(1,1) NOT NULL,
	EVENT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EVENT_DATE datetime DEFAULT getdate() NOT NULL,
	EVENT_USER_ID int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_MILESTONES PRIMARY KEY (MILESTONE_ID)
);


-- [GUARDIAN-DEV].dbo.ORGANIZATIONS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.ORGANIZATIONS;

CREATE TABLE [GUARDIAN-DEV].dbo.ORGANIZATIONS (
	ORGANIZATION_ID int IDENTITY(1,1) NOT NULL,
	COMPANY_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WORK_SPACE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	SysStartTime datetime2 DEFAULT sysutcdatetime() NOT NULL,
	SysEndTime datetime2 DEFAULT CONVERT([datetime2],'9999-12-31 23:59:59.9999999') NOT NULL,
	CONSTRAINT PK_ORGANIZATIONS PRIMARY KEY (ORGANIZATION_ID)
);


-- [GUARDIAN-DEV].dbo.ORGANIZATIONS_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.ORGANIZATIONS_HISTORY;

CREATE TABLE [GUARDIAN-DEV].dbo.ORGANIZATIONS_HISTORY (
	ORGANIZATION_ID int NOT NULL,
	COMPANY_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WORK_SPACE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL
);
 CREATE CLUSTERED INDEX ix_ORGANIZATIONS_HISTORY ON GUARDIAN-DEV.dbo.ORGANIZATIONS_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].dbo.REQUESTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.REQUESTS;

CREATE TABLE [GUARDIAN-DEV].dbo.REQUESTS (
	REQUEST_ID int IDENTITY(1,1) NOT NULL,
	REQUEST_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXTERNAL_USER char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NULL,
	SUBMITTED_DATE datetime DEFAULT getdate() NOT NULL,
	REQUESTOR_ID int NULL,
	ASSIGNED_ID int NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'A' NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	TRACKINGID nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABBREVIATION varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID decimal(38,0) NULL,
	REQUEST_DESCRIPTION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FORM_ID decimal(38,0) NULL,
	CONSTRAINT PK_REQUESTS PRIMARY KEY (REQUEST_ID)
);


-- [GUARDIAN-DEV].dbo.ROLES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.ROLES;

CREATE TABLE [GUARDIAN-DEV].dbo.ROLES (
	ROLE_ID int IDENTITY(1,1) NOT NULL,
	NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DISPLAY_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NULL,
	UPDATE_DATE datetime DEFAULT getdate() NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	CONSTRAINT ROLES_PK PRIMARY KEY (ROLE_ID)
);


-- [GUARDIAN-DEV].dbo.TASKS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.TASKS;

CREATE TABLE [GUARDIAN-DEV].dbo.TASKS (
	TASK_ID int IDENTITY(1,1) NOT NULL,
	REQUEST_ID int NOT NULL,
	STATUS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ASSIGNED_USER_ID int NOT NULL,
	DESCRIPTION varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	TRACKINGID nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_TASKS PRIMARY KEY (TASK_ID)
);


-- [GUARDIAN-DEV].dbo.TEST definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.TEST;

CREATE TABLE [GUARDIAN-DEV].dbo.TEST (
	ID int NULL,
	NAME varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);


-- [GUARDIAN-DEV].dbo.USERS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.USERS;

CREATE TABLE [GUARDIAN-DEV].dbo.USERS (
	USER_ID int IDENTITY(1,1) NOT NULL,
	FIRST_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LAST_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EMAIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PIN int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	SysStartTime datetime2 DEFAULT sysutcdatetime() NOT NULL,
	SysEndTime datetime2 DEFAULT CONVERT([datetime2],'9999-12-31 23:59:59.9999999') NOT NULL,
	PASSWORD_HASH varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL_VALIDATED bit DEFAULT 0 NOT NULL,
	EMAIL_VALIDATION_TOKEN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PASSWORD_RESET_TOKEN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID int NULL,
	EMAIL_VALIDATION_CODE_PLAIN varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL_VALIDATION_TOKEN_EXPIRY datetime2 NULL,
	PASSWORD_RESET_TOKEN_EXPIRY datetime2 NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);


-- [GUARDIAN-DEV].dbo.USER_ROLES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.USER_ROLES;

CREATE TABLE [GUARDIAN-DEV].dbo.USER_ROLES (
	USER_ROLE_ID int IDENTITY(1,1) NOT NULL,
	USER_ID int NOT NULL,
	ROLE_ID int NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NULL,
	UPDATE_DATE datetime DEFAULT getdate() NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ROLE_ID)
);


-- [GUARDIAN-DEV].dbo.[_prisma_migrations] definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.[_prisma_migrations];

CREATE TABLE [GUARDIAN-DEV].dbo.[_prisma_migrations] (
	id varchar(36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	checksum varchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	finished_at datetimeoffset NULL,
	migration_name nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	logs nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	rolled_back_at datetimeoffset NULL,
	started_at datetimeoffset DEFAULT getdate() NOT NULL,
	applied_steps_count int DEFAULT 0 NOT NULL,
	CONSTRAINT PK___prisma___3213E83F93FE285D PRIMARY KEY (id)
);


-- [GUARDIAN-DEV].dbo.COMPANY_INFO definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.COMPANY_INFO;

CREATE TABLE [GUARDIAN-DEV].dbo.COMPANY_INFO (
	COMPANY_INFO_ID int IDENTITY(1,1) NOT NULL,
	COMPANY_ID int NOT NULL,
	USER_ID int NOT NULL,
	WORKSPACE_NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROLE] nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEAM_SIZE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_SIZE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATED_AT datetime DEFAULT getdate() NOT NULL,
	UPDATED_AT datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK__COMPANY___2099A60865741D46 PRIMARY KEY (COMPANY_INFO_ID),
	CONSTRAINT FK_COMPANY_INFO_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].dbo.COMPANY(COMPANY_ID),
	CONSTRAINT FK_COMPANY_INFO_USERS FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].dbo.USERS(USER_ID)
);


-- [GUARDIAN-DEV].dbo.FORMS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].dbo.FORMS;

CREATE TABLE [GUARDIAN-DEV].dbo.FORMS (
	FORM_ID int IDENTITY(1,1) NOT NULL,
	FORM_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FORM_DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ORGANIZATION_ID int NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	IS_ACTIVE bit DEFAULT 0 NOT NULL,
	IS_DELETED bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	SysStartTime datetime2 DEFAULT sysutcdatetime() NOT NULL,
	SysEndTime datetime2 DEFAULT CONVERT([datetime2],'9999-12-31 23:59:59.9999999') NOT NULL,
	COMPANY_ID int NULL,
	CONSTRAINT PK_FORMS PRIMARY KEY (FORM_ID),
	CONSTRAINT FK__FORMS__COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].dbo.COMPANY(COMPANY_ID)
);