-- Create WORK_PROGRESS table for tracking detailed work progress on requests
-- This table supports detailed progress tracking, milestone marking, and file attachments

CREATE TABLE GUARDIAN.WORK_PROGRESS (
    WORK_PROGRESS_ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUEST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    PROGRESS_TYPE VARCHAR(50) NOT NULL DEFAULT 'note', -- 'note', 'milestone', 'discovery', 'attachment', 'status_update'
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    HOURS_WORKED DECIMAL(5,2),
    STATUS_UPDATE VARCHAR(100),
    RELATED_ATTACHMENT_ID INT,
    IS_MILESTONE BIT NOT NULL DEFAULT 0,
    IS_VISIBLE_TO_REQUESTOR BIT NOT NULL DEFAULT 1,
    CREATE_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATE_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CREATE_USER_ID INT,
    UPDATE_USER_ID INT,
    
    -- Foreign key constraints
    CONSTRAINT FK_WORK_PROGRESS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES GUARDIAN.REQUESTS(REQUEST_ID),
    CONSTRAINT FK_WORK_PROGRESS_USER FOREIGN KEY (USER_ID) REFERENCES GUARDIAN.USERS(USER_ID),
    CONSTRAINT FK_WORK_PROGRESS_ATTACHMENT FOREIGN KEY (RELATED_ATTACHMENT_ID) REFERENCES GUARDIAN.ATTACHMENTS(ATTACHMENT_ID)
);