-- Create indexes for WORK_PROGRESS table performance
CREATE INDEX IX_WORK_PROGRESS_REQUEST_ID ON GUARDIAN.WORK_PROGRESS(REQUEST_ID);
CREATE INDEX IX_WORK_PROGRESS_COMPANY_ID ON GUARDIAN.WORK_PROGRESS(COMPANY_ID);
CREATE INDEX IX_WORK_PROGRESS_USER_ID ON GUARDIAN.WORK_PROGRESS(USER_ID);
CREATE INDEX IX_WORK_PROGRESS_CREATE_DATE ON GUARDIAN.WORK_PROGRESS(CREATE_DATE);