-- Add trigger to update UPDATE_DATE on row changes
CREATE TRIGGER TR_WORK_PROGRESS_UPDATE_DATE
ON GUARDIAN.WORK_PROGRESS
AFTER UPDATE
AS
BEGIN
    UPDATE GUARDIAN.WORK_PROGRESS
    SET UPDATE_DATE = GETDATE()
    WHERE WORK_PROGRESS_ID IN (SELECT WORK_PROGRESS_ID FROM inserted);
END;