-- Update existing ATTACHMENTS records with company_id from related requests
UPDATE a 
SET a.COMPANY_ID = CAST(r.COMPANY_ID AS INT)
FROM GUARDIAN.ATTACHMENTS a
INNER JOIN GUARDIAN.REQUESTS r ON a.REQUEST_ID = r.REQUEST_ID
WHERE r.COMPANY_ID IS NOT NULL AND a.COMPANY_ID IS NULL;