-- Create index on ATTACHMENTS.COMPANY_ID for performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTACHMENTS_COMPANY_ID')
BEGIN
    CREATE INDEX IX_ATTACHMENTS_COMPANY_ID ON GUARDIAN.ATTACHMENTS(COMPANY_ID);
END;