-- Migration 30: Add ANALYST_ID and INVESTIGATOR_ID to GUARDIAN.REQUESTS
-- Allows Analyst and Investigator assignments on Fidelity-Subject forms to
-- appear in each user's "My Requests" queue.

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'GUARDIAN' AND TABLE_NAME = 'REQUESTS' AND COLUMN_NAME = 'ANALYST_ID'
)
BEGIN
    ALTER TABLE GUARDIAN.REQUESTS ADD ANALYST_ID INT NULL;
    PRINT 'Added ANALYST_ID column to REQUESTS.';
END
ELSE
    PRINT 'ANALYST_ID already exists.';

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'GUARDIAN' AND TABLE_NAME = 'REQUESTS' AND COLUMN_NAME = 'INVESTIGATOR_ID'
)
BEGIN
    ALTER TABLE GUARDIAN.REQUESTS ADD INVESTIGATOR_ID INT NULL;
    PRINT 'Added INVESTIGATOR_ID column to REQUESTS.';
END
ELSE
    PRINT 'INVESTIGATOR_ID already exists.';

PRINT 'Migration 30 complete.';
