-- Adds TEMPLATE_TYPE and STATUS columns to GUARDIAN.FORMS.
-- Idempotent: checks for column existence before adding.
-- Runs via scripts/run-migration.cjs (splits on "END;\n").

IF NOT EXISTS (
  SELECT 1 FROM sys.columns
  WHERE object_id = OBJECT_ID('GUARDIAN.FORMS') AND name = 'TEMPLATE_TYPE'
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD TEMPLATE_TYPE NVARCHAR(20) NULL;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.columns
  WHERE object_id = OBJECT_ID('GUARDIAN.FORMS') AND name = 'STATUS'
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD STATUS NVARCHAR(20) NULL;
END;

-- Backfill TEMPLATE_TYPE on rows that predate this column.
IF EXISTS (
  SELECT 1 FROM GUARDIAN.FORMS WHERE TEMPLATE_TYPE IS NULL
)
BEGIN
  UPDATE GUARDIAN.FORMS SET TEMPLATE_TYPE = 'request' WHERE TEMPLATE_TYPE IS NULL;
END;

-- Backfill STATUS from IS_ACTIVE on rows that predate this column.
IF EXISTS (
  SELECT 1 FROM GUARDIAN.FORMS WHERE STATUS IS NULL
)
BEGIN
  UPDATE GUARDIAN.FORMS
    SET STATUS = CASE WHEN IS_ACTIVE = 1 THEN 'active' ELSE 'inactive' END
    WHERE STATUS IS NULL;
END;

-- Enforce NOT NULL + defaults now that all rows have values.
IF EXISTS (
  SELECT 1 FROM sys.columns
  WHERE object_id = OBJECT_ID('GUARDIAN.FORMS') AND name = 'TEMPLATE_TYPE' AND is_nullable = 1
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ALTER COLUMN TEMPLATE_TYPE NVARCHAR(20) NOT NULL;
END;

IF EXISTS (
  SELECT 1 FROM sys.columns
  WHERE object_id = OBJECT_ID('GUARDIAN.FORMS') AND name = 'STATUS' AND is_nullable = 1
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ALTER COLUMN STATUS NVARCHAR(20) NOT NULL;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.default_constraints WHERE name = 'DF_FORMS_TEMPLATE_TYPE'
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT DF_FORMS_TEMPLATE_TYPE DEFAULT 'request' FOR TEMPLATE_TYPE;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.default_constraints WHERE name = 'DF_FORMS_STATUS'
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT DF_FORMS_STATUS DEFAULT 'draft' FOR STATUS;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.check_constraints WHERE name = 'CK_FORMS_TEMPLATE_TYPE'
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT CK_FORMS_TEMPLATE_TYPE
    CHECK (TEMPLATE_TYPE IN ('notice','request'));
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.check_constraints WHERE name = 'CK_FORMS_STATUS'
)
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT CK_FORMS_STATUS
    CHECK (STATUS IN ('draft','active','inactive'));
END;
