-- Finishes the TEMPLATE_TYPE / STATUS rollout on GUARDIAN.FORMS.
-- The initial migration added nullable columns + backfilled the current rows,
-- but ALTER COLUMN ... NOT NULL fails because the system-versioned history
-- table (GUARDIAN.FORMS_HISTORY) has rows with NULLs. This script turns off
-- SYSTEM_VERSIONING, backfills history, alters both tables, re-enables.

ALTER TABLE GUARDIAN.FORMS SET (SYSTEM_VERSIONING = OFF);

UPDATE GUARDIAN.FORMS_HISTORY
  SET TEMPLATE_TYPE = 'request'
  WHERE TEMPLATE_TYPE IS NULL;

UPDATE GUARDIAN.FORMS_HISTORY
  SET STATUS = CASE WHEN IS_ACTIVE = 1 THEN 'active' ELSE 'inactive' END
  WHERE STATUS IS NULL;

ALTER TABLE GUARDIAN.FORMS ALTER COLUMN TEMPLATE_TYPE NVARCHAR(20) NOT NULL;
ALTER TABLE GUARDIAN.FORMS ALTER COLUMN STATUS NVARCHAR(20) NOT NULL;

ALTER TABLE GUARDIAN.FORMS_HISTORY ALTER COLUMN TEMPLATE_TYPE NVARCHAR(20) NOT NULL;
ALTER TABLE GUARDIAN.FORMS_HISTORY ALTER COLUMN STATUS NVARCHAR(20) NOT NULL;

ALTER TABLE GUARDIAN.FORMS SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = GUARDIAN.FORMS_HISTORY));

IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE name = 'DF_FORMS_TEMPLATE_TYPE')
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT DF_FORMS_TEMPLATE_TYPE DEFAULT 'request' FOR TEMPLATE_TYPE;
END;

IF NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE name = 'DF_FORMS_STATUS')
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT DF_FORMS_STATUS DEFAULT 'draft' FOR STATUS;
END;

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_FORMS_TEMPLATE_TYPE')
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT CK_FORMS_TEMPLATE_TYPE
    CHECK (TEMPLATE_TYPE IN ('notice','request'));
END;

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_FORMS_STATUS')
BEGIN
  ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT CK_FORMS_STATUS
    CHECK (STATUS IN ('draft','active','inactive'));
END;
