-- Create WORK_PROGRESS table for tracking detailed work progress on requests
-- This table supports detailed progress tracking, milestone marking, and file attachments

CREATE TABLE GUARDIAN.WORK_PROGRESS (
    WORK_PROGRESS_ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUEST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    PROGRESS_TYPE VARCHAR(50) NOT NULL DEFAULT 'note', -- 'note', 'milestone', 'discovery', 'attachment', 'status_update'
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    HOURS_WORKED DECIMAL(5,2),
    STATUS_UPDATE VARCHAR(100),
    RELATED_ATTACHMENT_ID INT,
    IS_MILESTONE BIT NOT NULL DEFAULT 0,
    IS_VISIBLE_TO_REQUESTOR BIT NOT NULL DEFAULT 1,
    CREATE_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATE_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CREATE_USER_ID INT,
    UPDATE_USER_ID INT,
    
    -- Foreign key constraints
    CONSTRAINT FK_WORK_PROGRESS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES GUARDIAN.REQUESTS(REQUEST_ID),
    CONSTRAINT FK_WORK_PROGRESS_USER FOREIGN KEY (USER_ID) REFERENCES GUARDIAN.USERS(USER_ID),
    CONSTRAINT FK_WORK_PROGRESS_ATTACHMENT FOREIGN KEY (RELATED_ATTACHMENT_ID) REFERENCES GUARDIAN.ATTACHMENTS(ATTACHMENT_ID),
    
    -- Indexes for performance
    INDEX IX_WORK_PROGRESS_REQUEST_ID (REQUEST_ID),
    INDEX IX_WORK_PROGRESS_COMPANY_ID (COMPANY_ID),
    INDEX IX_WORK_PROGRESS_USER_ID (USER_ID),
    INDEX IX_WORK_PROGRESS_CREATE_DATE (CREATE_DATE)
);

-- Add trigger to update UPDATE_DATE on row changes
CREATE TRIGGER TR_WORK_PROGRESS_UPDATE_DATE
ON GUARDIAN.WORK_PROGRESS
AFTER UPDATE
AS
BEGIN
    UPDATE GUARDIAN.WORK_PROGRESS
    SET UPDATE_DATE = GETDATE()
    WHERE WORK_PROGRESS_ID IN (SELECT WORK_PROGRESS_ID FROM inserted);
END;

-- Add company_id column to ATTACHMENTS table if it doesn't exist (for proper company isolation)
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GUARDIAN.ATTACHMENTS') AND name = 'COMPANY_ID')
BEGIN
    ALTER TABLE GUARDIAN.ATTACHMENTS ADD COMPANY_ID INT;
    -- Update existing records with company_id from related requests
    UPDATE a 
    SET a.COMPANY_ID = CAST(r.COMPANY_ID AS INT)
    FROM GUARDIAN.ATTACHMENTS a
    INNER JOIN GUARDIAN.REQUESTS r ON a.REQUEST_ID = r.REQUEST_ID
    WHERE r.COMPANY_ID IS NOT NULL;
END;

-- Create index on ATTACHMENTS.COMPANY_ID for performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ATTACHMENTS_COMPANY_ID')
BEGIN
    CREATE INDEX IX_ATTACHMENTS_COMPANY_ID ON GUARDIAN.ATTACHMENTS(COMPANY_ID);
END;

GO