-- Guardian MVP Notice Module Migration
-- Date: 2024-08-18
-- Description: Creates tables for the Notice Module including NOTICES, NOTICE_RECIPIENTS, and NOTICE_READ_STATUS

-- Create NOTICES table
CREATE TABLE [GUARDIAN].[NOTICES] (
    [NOTICE_ID] int IDENTITY(1,1) NOT NULL,
    [TITLE] nvarchar(255) NOT NULL,
    [CONTENT] nvarchar(4000) NOT NULL,
    [NOTICE_TYPE] nvarchar(50) NOT NULL,
    [STATUS] nvarchar(20) NOT NULL DEFAULT 'DRAFT',
    [ISSUED_BY_USER_ID] int NOT NULL,
    [ISSUE_DATE] datetime2,
    [COMPANY_ID] int NOT NULL,
    [FORM_TEMPLATE_ID] int,
    [CANCELLATION_REASON] nvarchar(500),
    [IS_ACTIVE] bit NOT NULL DEFAULT 1,
    [IS_DELETED] bit NOT NULL DEFAULT 0,
    [CREATE_DATE] datetime2 NOT NULL DEFAULT getdate(),
    [UPDATE_DATE] datetime2 NOT NULL DEFAULT getdate(),
    [CREATE_USER_ID] int,
    [UPDATE_USER_ID] int,
    CONSTRAINT [PK_NOTICES] PRIMARY KEY ([NOTICE_ID])
);

-- Create NOTICE_RECIPIENTS table
CREATE TABLE [GUARDIAN].[NOTICE_RECIPIENTS] (
    [NOTICE_RECIPIENT_ID] int IDENTITY(1,1) NOT NULL,
    [NOTICE_ID] int NOT NULL,
    [RECIPIENT_USER_ID] int NOT NULL,
    [RECIPIENT_TYPE] nvarchar(20) NOT NULL DEFAULT 'USER',
    [COMPANY_ID] int NOT NULL,
    [CREATE_DATE] datetime2 NOT NULL DEFAULT getdate(),
    [CREATE_USER_ID] int,
    CONSTRAINT [PK_NOTICE_RECIPIENTS] PRIMARY KEY ([NOTICE_RECIPIENT_ID]),
    CONSTRAINT [UQ_NOTICE_RECIPIENTS_UNIQUE] UNIQUE ([NOTICE_ID], [RECIPIENT_USER_ID])
);

-- Create NOTICE_READ_STATUS table
CREATE TABLE [GUARDIAN].[NOTICE_READ_STATUS] (
    [NOTICE_READ_STATUS_ID] int IDENTITY(1,1) NOT NULL,
    [NOTICE_ID] int NOT NULL,
    [USER_ID] int NOT NULL,
    [READ_DATE] datetime2 NOT NULL DEFAULT getdate(),
    [COMPANY_ID] int NOT NULL,
    [CREATE_DATE] datetime2 NOT NULL DEFAULT getdate(),
    CONSTRAINT [PK_NOTICE_READ_STATUS] PRIMARY KEY ([NOTICE_READ_STATUS_ID]),
    CONSTRAINT [UQ_NOTICE_READ_STATUS_UNIQUE] UNIQUE ([NOTICE_ID], [USER_ID])
);

-- Add foreign key constraints
ALTER TABLE [GUARDIAN].[NOTICES] ADD CONSTRAINT [FK_NOTICES_ISSUED_BY_USER] 
    FOREIGN KEY ([ISSUED_BY_USER_ID]) REFERENCES [GUARDIAN].[USERS]([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [GUARDIAN].[NOTICES] ADD CONSTRAINT [FK_NOTICES_FORM_TEMPLATE] 
    FOREIGN KEY ([FORM_TEMPLATE_ID]) REFERENCES [GUARDIAN].[FORMS]([FORM_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [GUARDIAN].[NOTICE_RECIPIENTS] ADD CONSTRAINT [FK_NOTICE_RECIPIENTS_NOTICE] 
    FOREIGN KEY ([NOTICE_ID]) REFERENCES [GUARDIAN].[NOTICES]([NOTICE_ID]) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE [GUARDIAN].[NOTICE_RECIPIENTS] ADD CONSTRAINT [FK_NOTICE_RECIPIENTS_USER] 
    FOREIGN KEY ([RECIPIENT_USER_ID]) REFERENCES [GUARDIAN].[USERS]([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [GUARDIAN].[NOTICE_READ_STATUS] ADD CONSTRAINT [FK_NOTICE_READ_STATUS_NOTICE] 
    FOREIGN KEY ([NOTICE_ID]) REFERENCES [GUARDIAN].[NOTICES]([NOTICE_ID]) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE [GUARDIAN].[NOTICE_READ_STATUS] ADD CONSTRAINT [FK_NOTICE_READ_STATUS_USER] 
    FOREIGN KEY ([USER_ID]) REFERENCES [GUARDIAN].[USERS]([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Create indexes for performance
CREATE INDEX [IX_NOTICES_COMPANY_ID] ON [GUARDIAN].[NOTICES] ([COMPANY_ID]);
CREATE INDEX [IX_NOTICES_ISSUED_BY_USER_ID] ON [GUARDIAN].[NOTICES] ([ISSUED_BY_USER_ID]);
CREATE INDEX [IX_NOTICES_STATUS] ON [GUARDIAN].[NOTICES] ([STATUS]);
CREATE INDEX [IX_NOTICES_ISSUE_DATE] ON [GUARDIAN].[NOTICES] ([ISSUE_DATE]);

CREATE INDEX [IX_NOTICE_RECIPIENTS_COMPANY_ID] ON [GUARDIAN].[NOTICE_RECIPIENTS] ([COMPANY_ID]);
CREATE INDEX [IX_NOTICE_RECIPIENTS_RECIPIENT_USER_ID] ON [GUARDIAN].[NOTICE_RECIPIENTS] ([RECIPIENT_USER_ID]);

CREATE INDEX [IX_NOTICE_READ_STATUS_COMPANY_ID] ON [GUARDIAN].[NOTICE_READ_STATUS] ([COMPANY_ID]);
CREATE INDEX [IX_NOTICE_READ_STATUS_USER_ID] ON [GUARDIAN].[NOTICE_READ_STATUS] ([USER_ID]);

-- Add update trigger for NOTICES table to auto-update UPDATE_DATE
CREATE TRIGGER [tr_NOTICES_UpdateDate] ON [GUARDIAN].[NOTICES]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE [GUARDIAN].[NOTICES] 
    SET [UPDATE_DATE] = getdate()
    FROM [GUARDIAN].[NOTICES] n
    INNER JOIN inserted i ON n.[NOTICE_ID] = i.[NOTICE_ID];
END;