-- Migration: Add COMPANY_ID to MY_NOTICES, NOTICE_RECIPIENTS, RESPONSE_MY_NOTICE
-- Purpose: Direct company isolation instead of JOINing through USERS table
-- Date: 2026-03-27

-- ============================================================
-- 1. MY_NOTICES
-- ============================================================
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'GUARDIAN' AND TABLE_NAME = 'MY_NOTICES' AND COLUMN_NAME = 'COMPANY_ID'
)
BEGIN
  ALTER TABLE GUARDIAN.MY_NOTICES ADD COMPANY_ID INT NULL;
END
GO

-- Backfill from CREATE_USER_ID -> USERS.COMPANY_ID
UPDATE n
SET n.COMPANY_ID = u.COMPANY_ID
FROM GUARDIAN.MY_NOTICES n
INNER JOIN GUARDIAN.USERS u ON n.CREATE_USER_ID = u.USER_ID
WHERE n.COMPANY_ID IS NULL;
GO

-- Foreign key
IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MY_NOTICES_COMPANY'
)
BEGIN
  ALTER TABLE GUARDIAN.MY_NOTICES ADD CONSTRAINT FK_MY_NOTICES_COMPANY
    FOREIGN KEY (COMPANY_ID) REFERENCES GUARDIAN.COMPANY(COMPANY_ID);
END
GO

-- Index for fast filtering
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = 'IX_MY_NOTICES_COMPANY_ID'
)
BEGIN
  CREATE INDEX IX_MY_NOTICES_COMPANY_ID ON GUARDIAN.MY_NOTICES(COMPANY_ID);
END
GO

-- ============================================================
-- 2. NOTICE_RECIPIENTS
-- ============================================================
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'GUARDIAN' AND TABLE_NAME = 'NOTICE_RECIPIENTS' AND COLUMN_NAME = 'COMPANY_ID'
)
BEGIN
  ALTER TABLE GUARDIAN.NOTICE_RECIPIENTS ADD COMPANY_ID INT NULL;
END
GO

-- Backfill from parent notice
UPDATE nr
SET nr.COMPANY_ID = n.COMPANY_ID
FROM GUARDIAN.NOTICE_RECIPIENTS nr
INNER JOIN GUARDIAN.MY_NOTICES n ON nr.NOTICE_ID = n.NOTICE_ID
WHERE nr.COMPANY_ID IS NULL;
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_NOTICE_RECIPIENTS_COMPANY'
)
BEGIN
  ALTER TABLE GUARDIAN.NOTICE_RECIPIENTS ADD CONSTRAINT FK_NOTICE_RECIPIENTS_COMPANY
    FOREIGN KEY (COMPANY_ID) REFERENCES GUARDIAN.COMPANY(COMPANY_ID);
END
GO

-- ============================================================
-- 3. RESPONSE_MY_NOTICE
-- ============================================================
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'GUARDIAN' AND TABLE_NAME = 'RESPONSE_MY_NOTICE' AND COLUMN_NAME = 'COMPANY_ID'
)
BEGIN
  ALTER TABLE GUARDIAN.RESPONSE_MY_NOTICE ADD COMPANY_ID INT NULL;
END
GO

-- Backfill from parent notice
UPDATE r
SET r.COMPANY_ID = n.COMPANY_ID
FROM GUARDIAN.RESPONSE_MY_NOTICE r
INNER JOIN GUARDIAN.MY_NOTICES n ON r.MY_NOTICE_ID = n.NOTICE_ID
WHERE r.COMPANY_ID IS NULL;
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RESPONSE_MY_NOTICE_COMPANY'
)
BEGIN
  ALTER TABLE GUARDIAN.RESPONSE_MY_NOTICE ADD CONSTRAINT FK_RESPONSE_MY_NOTICE_COMPANY
    FOREIGN KEY (COMPANY_ID) REFERENCES GUARDIAN.COMPANY(COMPANY_ID);
END
GO
