-- Migration: Create Workspace Management System
-- Date: 2025-08-28
-- Description: Add workspace tables and update existing tables to support workspace-based data compartmentalization

-- Create WORKSPACES table
CREATE TABLE GUARDIAN.WORKSPACES (
    WORKSPACE_ID int IDENTITY(1,1) PRIMARY KEY,
    WORKSPACE_NAME nvarchar(100) NOT NULL,
    DESCRIPTION nvarchar(500) NULL,
    COMPANY_ID int NOT NULL,
    IS_ACTIVE bit NOT NULL DEFAULT 1,
    IS_DEFAULT bit NOT NULL DEFAULT 0,
    CREATE_USER_ID int NULL,
    UPDATE_USER_ID int NULL,
    CREATE_DATE datetime2 NOT NULL DEFAULT GETDATE(),
    UPDATE_DATE datetime2 NOT NULL DEFAULT GETDATE(),
    
    -- Constraints
    CONSTRAINT UQ_WORKSPACES_COMPANY_NAME UNIQUE (COMPANY_ID, WORKSPACE_NAME)
);

-- Create indexes for WORKSPACES
CREATE INDEX IX_WORKSPACES_COMPANY_ACTIVE ON GUARDIAN.WORKSPACES (COMPANY_ID, IS_ACTIVE);

-- Create USER_WORKSPACES junction table
CREATE TABLE GUARDIAN.USER_WORKSPACES (
    USER_WORKSPACE_ID int IDENTITY(1,1) PRIMARY KEY,
    USER_ID int NOT NULL,
    WORKSPACE_ID int NOT NULL,
    IS_ACTIVE bit NOT NULL DEFAULT 1,
    IS_DEFAULT bit NOT NULL DEFAULT 0,
    CREATE_USER_ID int NULL,
    UPDATE_USER_ID int NULL,
    CREATE_DATE datetime2 NOT NULL DEFAULT GETDATE(),
    UPDATE_DATE datetime2 NOT NULL DEFAULT GETDATE(),
    
    -- Foreign key constraints
    CONSTRAINT FK_USER_WORKSPACES_USER FOREIGN KEY (USER_ID) REFERENCES GUARDIAN.USERS (USER_ID),
    CONSTRAINT FK_USER_WORKSPACES_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES GUARDIAN.WORKSPACES (WORKSPACE_ID),
    
    -- Unique constraint to prevent duplicate user-workspace assignments
    CONSTRAINT UQ_USER_WORKSPACES_USER_WORKSPACE UNIQUE (USER_ID, WORKSPACE_ID)
);

-- Create indexes for USER_WORKSPACES
CREATE INDEX IX_USER_WORKSPACES_USER_ACTIVE ON GUARDIAN.USER_WORKSPACES (USER_ID, IS_ACTIVE);
CREATE INDEX IX_USER_WORKSPACES_WORKSPACE_ACTIVE ON GUARDIAN.USER_WORKSPACES (WORKSPACE_ID, IS_ACTIVE);

-- Add workspace columns to existing tables
-- Add ACTIVE_WORKSPACE_ID to USERS table
ALTER TABLE GUARDIAN.USERS ADD ACTIVE_WORKSPACE_ID int NULL;

-- Add WORKSPACE_ID to REQUESTS table
ALTER TABLE GUARDIAN.REQUESTS ADD WORKSPACE_ID int NULL;

-- Add WORKSPACE_ID to FORMS table
ALTER TABLE GUARDIAN.FORMS ADD WORKSPACE_ID int NULL;

-- Add WORKSPACE_ID to NOTICES table
ALTER TABLE GUARDIAN.NOTICES ADD WORKSPACE_ID int NULL;

-- Add foreign key constraints for workspace references
ALTER TABLE GUARDIAN.REQUESTS ADD CONSTRAINT FK_REQUESTS_WORKSPACE 
    FOREIGN KEY (WORKSPACE_ID) REFERENCES GUARDIAN.WORKSPACES (WORKSPACE_ID);

ALTER TABLE GUARDIAN.FORMS ADD CONSTRAINT FK_FORMS_WORKSPACE 
    FOREIGN KEY (WORKSPACE_ID) REFERENCES GUARDIAN.WORKSPACES (WORKSPACE_ID);

ALTER TABLE GUARDIAN.NOTICES ADD CONSTRAINT FK_NOTICES_WORKSPACE 
    FOREIGN KEY (WORKSPACE_ID) REFERENCES GUARDIAN.WORKSPACES (WORKSPACE_ID);

-- Create indexes for workspace filtering
CREATE INDEX IX_REQUESTS_WORKSPACE ON GUARDIAN.REQUESTS (WORKSPACE_ID);
CREATE INDEX IX_FORMS_WORKSPACE ON GUARDIAN.FORMS (WORKSPACE_ID);
CREATE INDEX IX_NOTICES_WORKSPACE ON GUARDIAN.NOTICES (WORKSPACE_ID);

PRINT 'Workspace system tables created successfully';