-- Guardian MVP Notice Management System
-- Date: 2026-03-26
-- Description: Creates MY_NOTICES, NOTICE_RECIPIENTS, and RESPONSE_MY_NOTICE tables

-- MY_NOTICES table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'MY_NOTICES' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[MY_NOTICES] (
        [NOTICE_ID]                  INT IDENTITY(1,1) NOT NULL,
        [NOTICE_TITLE]               NVARCHAR(255) NOT NULL,
        [SENSITIVITY_CLASSIFICATION] NVARCHAR(50) NOT NULL,
        [BUTTON_STATUS]              NVARCHAR(50) NOT NULL,
        [DISTRIBUTION_TYPE]          NVARCHAR(50) NULL,
        [NOTICE_BODY]                NVARCHAR(MAX) NULL,
        [CREATE_USER_ID]             INT NULL,
        [UPDATE_USER_ID]             INT NULL,
        [CREATE_DATE]                DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [UPDATE_DATE]                DATETIME2 NULL,

        CONSTRAINT [PK_MY_NOTICES] PRIMARY KEY CLUSTERED ([NOTICE_ID] ASC),
        CONSTRAINT [FK_MY_NOTICES_CREATE_USER] FOREIGN KEY ([CREATE_USER_ID])
            REFERENCES [GUARDIAN].[USERS] ([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT [FK_MY_NOTICES_UPDATE_USER] FOREIGN KEY ([UPDATE_USER_ID])
            REFERENCES [GUARDIAN].[USERS] ([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    PRINT 'Created GUARDIAN.MY_NOTICES table';
END
ELSE
    PRINT 'GUARDIAN.MY_NOTICES already exists, skipping';

-- NOTICE_RECIPIENTS table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NOTICE_RECIPIENTS' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[NOTICE_RECIPIENTS] (
        [NOTICE_RECIPIENT_ID] INT IDENTITY(1,1) NOT NULL,
        [NOTICE_ID]           INT NOT NULL,
        [USER_ID]             INT NOT NULL,

        CONSTRAINT [PK_NOTICE_RECIPIENTS] PRIMARY KEY CLUSTERED ([NOTICE_RECIPIENT_ID] ASC),
        CONSTRAINT [FK_NOTICE_RECIPIENTS_NOTICE] FOREIGN KEY ([NOTICE_ID])
            REFERENCES [GUARDIAN].[MY_NOTICES] ([NOTICE_ID]) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT [FK_NOTICE_RECIPIENTS_USER] FOREIGN KEY ([USER_ID])
            REFERENCES [GUARDIAN].[USERS] ([USER_ID]) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT [UQ_NOTICE_RECIPIENTS] UNIQUE ([NOTICE_ID], [USER_ID])
    );
    PRINT 'Created GUARDIAN.NOTICE_RECIPIENTS table';
END
ELSE
    PRINT 'GUARDIAN.NOTICE_RECIPIENTS already exists, skipping';

-- RESPONSE_MY_NOTICE table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'RESPONSE_MY_NOTICE' AND SCHEMA_NAME(schema_id) = 'GUARDIAN')
BEGIN
    CREATE TABLE [GUARDIAN].[RESPONSE_MY_NOTICE] (
        [RESPONSE_MY_NOTICE_ID] INT IDENTITY(1,1) NOT NULL,
        [MY_NOTICE_ID]          INT NOT NULL,
        [USER_ID]               INT NOT NULL,
        [RESPONSE_TEXT]         NVARCHAR(MAX) NULL,
        [ATTACHMENT_ID]         INT NULL,
        [CREATE_DATE]           DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_RESPONSE_MY_NOTICE] PRIMARY KEY CLUSTERED ([RESPONSE_MY_NOTICE_ID] ASC),
        CONSTRAINT [FK_RESPONSE_MY_NOTICE_NOTICE] FOREIGN KEY ([MY_NOTICE_ID])
            REFERENCES [GUARDIAN].[MY_NOTICES] ([NOTICE_ID]) ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT [FK_RESPONSE_MY_NOTICE_USER] FOREIGN KEY ([USER_ID])
            REFERENCES [GUARDIAN].[USERS] ([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT [FK_RESPONSE_MY_NOTICE_ATTACHMENT] FOREIGN KEY ([ATTACHMENT_ID])
            REFERENCES [GUARDIAN].[ATTACHMENTS] ([ATTACHMENT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    PRINT 'Created GUARDIAN.RESPONSE_MY_NOTICE table';
END
ELSE
    PRINT 'GUARDIAN.RESPONSE_MY_NOTICE already exists, skipping';

-- Indexes
CREATE INDEX [IX_MY_NOTICES_CREATE_USER_ID] ON [GUARDIAN].[MY_NOTICES] ([CREATE_USER_ID]);
CREATE INDEX [IX_MY_NOTICES_BUTTON_STATUS] ON [GUARDIAN].[MY_NOTICES] ([BUTTON_STATUS]);
CREATE INDEX [IX_NOTICE_RECIPIENTS_NOTICE_ID] ON [GUARDIAN].[NOTICE_RECIPIENTS] ([NOTICE_ID]);
CREATE INDEX [IX_NOTICE_RECIPIENTS_USER_ID] ON [GUARDIAN].[NOTICE_RECIPIENTS] ([USER_ID]);
CREATE INDEX [IX_RESPONSE_MY_NOTICE_MY_NOTICE_ID] ON [GUARDIAN].[RESPONSE_MY_NOTICE] ([MY_NOTICE_ID]);
