-- Migration: Populate Default Workspaces for Existing Companies
-- Date: 2025-08-28
-- Description: Create default workspaces for all existing companies and assign all users to them

-- Create a default workspace for each company
INSERT INTO GUARDIAN.WORKSPACES (WORKSPACE_NAME, DESCRIPTION, COMPANY_ID, IS_ACTIVE, IS_DEFAULT, CREATE_DATE, UPDATE_DATE)
SELECT 
    'Default Workspace' as WORKSPACE_NAME,
    'Default workspace created during system migration' as DESCRIPTION,
    c.COMPANY_ID,
    1 as IS_ACTIVE,
    1 as IS_DEFAULT,
    GETDATE() as CREATE_DATE,
    GETDATE() as UPDATE_DATE
FROM GUARDIAN.COMPANY c
WHERE NOT EXISTS (
    SELECT 1 FROM GUARDIAN.WORKSPACES w 
    WHERE w.COMPANY_ID = c.COMPANY_ID AND w.IS_DEFAULT = 1
);

-- Assign all existing users to their company's default workspace
INSERT INTO GUARDIAN.USER_WORKSPACES (USER_ID, WORKSPACE_ID, IS_ACTIVE, IS_DEFAULT, CREATE_DATE, UPDATE_DATE)
SELECT 
    u.USER_ID,
    w.WORKSPACE_ID,
    1 as IS_ACTIVE,
    1 as IS_DEFAULT,
    GETDATE() as CREATE_DATE,
    GETDATE() as UPDATE_DATE
FROM GUARDIAN.USERS u
INNER JOIN GUARDIAN.WORKSPACES w ON u.COMPANY_ID = w.COMPANY_ID AND w.IS_DEFAULT = 1
WHERE u.COMPANY_ID IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM GUARDIAN.USER_WORKSPACES uw 
    WHERE uw.USER_ID = u.USER_ID AND uw.WORKSPACE_ID = w.WORKSPACE_ID
);

-- Set users' active workspace to their default workspace
UPDATE GUARDIAN.USERS 
SET ACTIVE_WORKSPACE_ID = w.WORKSPACE_ID
FROM GUARDIAN.USERS u
INNER JOIN GUARDIAN.WORKSPACES w ON u.COMPANY_ID = w.COMPANY_ID AND w.IS_DEFAULT = 1
WHERE u.COMPANY_ID IS NOT NULL
AND u.ACTIVE_WORKSPACE_ID IS NULL;

-- Associate existing requests with default workspaces
UPDATE GUARDIAN.REQUESTS 
SET WORKSPACE_ID = w.WORKSPACE_ID
FROM GUARDIAN.REQUESTS r
INNER JOIN GUARDIAN.USERS u ON r.REQUESTOR_ID = u.USER_ID
INNER JOIN GUARDIAN.WORKSPACES w ON u.COMPANY_ID = w.COMPANY_ID AND w.IS_DEFAULT = 1
WHERE r.WORKSPACE_ID IS NULL
AND r.COMPANY_ID IS NOT NULL;

-- Associate existing forms with default workspaces  
UPDATE GUARDIAN.FORMS 
SET WORKSPACE_ID = w.WORKSPACE_ID
FROM GUARDIAN.FORMS f
INNER JOIN GUARDIAN.WORKSPACES w ON f.COMPANY_ID = w.COMPANY_ID AND w.IS_DEFAULT = 1
WHERE f.WORKSPACE_ID IS NULL
AND f.COMPANY_ID IS NOT NULL;

-- Associate existing notices with default workspaces
UPDATE GUARDIAN.NOTICES 
SET WORKSPACE_ID = w.WORKSPACE_ID
FROM GUARDIAN.NOTICES n
INNER JOIN GUARDIAN.WORKSPACES w ON n.COMPANY_ID = w.COMPANY_ID AND w.IS_DEFAULT = 1
WHERE n.WORKSPACE_ID IS NULL
AND n.COMPANY_ID IS NOT NULL;

-- Print summary of migration
SELECT 
    'Default workspaces created: ' + CAST(COUNT(*) AS varchar) as Summary
FROM GUARDIAN.WORKSPACES 
WHERE IS_DEFAULT = 1;

SELECT 
    'Users assigned to workspaces: ' + CAST(COUNT(*) AS varchar) as Summary
FROM GUARDIAN.USER_WORKSPACES 
WHERE IS_DEFAULT = 1;

PRINT 'Default workspace migration completed successfully';