-- =====================================================
-- Enhanced Milestone Tracking System Migration
-- Guardian MVP - WORK_PROGRESS Table Enhancement
-- Date: 2025-08-22
-- =====================================================

-- Add new milestone tracking fields to WORK_PROGRESS table
ALTER TABLE GUARDIAN.WORK_PROGRESS 
ADD 
    IS_SYSTEM_GENERATED BIT DEFAULT 0 NOT NULL,
    RELATED_TASK_ID INT NULL,
    STATUS_FROM VARCHAR(50) NULL,
    STATUS_TO VARCHAR(50) NULL,
    EVENT_DATA VARCHAR(4000) NULL;

-- Add helpful comments to document the enhanced functionality
EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'Enhanced to support comprehensive milestone tracking. PROGRESS_TYPE values: note, milestone, status, task, document, form, system', 
    @level0type = N'Schema', @level0name = N'GUARDIAN',
    @level1type = N'Table', @level1name = N'WORK_PROGRESS',
    @level2type = N'Column', @level2name = N'PROGRESS_TYPE';

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'Indicates if this milestone was automatically generated by the system', 
    @level0type = N'Schema', @level0name = N'GUARDIAN',
    @level1type = N'Table', @level1name = N'WORK_PROGRESS',
    @level2type = N'Column', @level2name = N'IS_SYSTEM_GENERATED';

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'Links to related task if this milestone is task-related', 
    @level0type = N'Schema', @level0name = N'GUARDIAN',
    @level1type = N'Table', @level1name = N'WORK_PROGRESS',
    @level2type = N'Column', @level2name = N'RELATED_TASK_ID';

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'Previous status for status change milestones', 
    @level0type = N'Schema', @level0name = N'GUARDIAN',
    @level1type = N'Table', @level1name = N'WORK_PROGRESS',
    @level2type = N'Column', @level2name = N'STATUS_FROM';

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'New status for status change milestones', 
    @level0type = N'Schema', @level0name = N'GUARDIAN',
    @level1type = N'Table', @level1name = N'WORK_PROGRESS',
    @level2type = N'Column', @level2name = N'STATUS_TO';

EXEC sp_addextendedproperty 
    @name = N'MS_Description', 
    @value = N'JSON data for additional context and metadata', 
    @level0type = N'Schema', @level0name = N'GUARDIAN',
    @level1type = N'Table', @level1name = N'WORK_PROGRESS',
    @level2type = N'Column', @level2name = N'EVENT_DATA';

-- Create performance indexes for milestone tracking queries (only if they don't exist)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_WORK_PROGRESS_REQUEST_COMPANY')
    CREATE INDEX IX_WORK_PROGRESS_REQUEST_COMPANY 
    ON GUARDIAN.WORK_PROGRESS (REQUEST_ID, COMPANY_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_WORK_PROGRESS_PROGRESS_TYPE')
    CREATE INDEX IX_WORK_PROGRESS_PROGRESS_TYPE 
    ON GUARDIAN.WORK_PROGRESS (PROGRESS_TYPE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_WORK_PROGRESS_IS_MILESTONE')
    CREATE INDEX IX_WORK_PROGRESS_IS_MILESTONE 
    ON GUARDIAN.WORK_PROGRESS (IS_MILESTONE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_WORK_PROGRESS_CREATE_DATE')
    CREATE INDEX IX_WORK_PROGRESS_CREATE_DATE 
    ON GUARDIAN.WORK_PROGRESS (CREATE_DATE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_WORK_PROGRESS_SYSTEM_GENERATED')
    CREATE INDEX IX_WORK_PROGRESS_SYSTEM_GENERATED 
    ON GUARDIAN.WORK_PROGRESS (IS_SYSTEM_GENERATED);

-- Create sample milestone types for better organization
-- These will be enforced in the application layer
PRINT 'Enhanced WORK_PROGRESS table for comprehensive milestone tracking:';
PRINT '- note: Manual progress notes';
PRINT '- milestone: Important milestone markers';
PRINT '- status: Status change events';
PRINT '- task: Task-related events';
PRINT '- document: File/attachment events';
PRINT '- form: Form submission/update events';
PRINT '- system: Automatic system-generated events';

PRINT 'Migration completed successfully!';