-- Migration: Add USER_LOGIN_EVENTS table for site analysis login tracking
-- Matches convention of 20250428-allow-null-request-relations.sql: hand-written,
-- manually applied to each environment (dev/staging/prod).

CREATE TABLE GUARDIAN.USER_LOGIN_EVENTS (
    EVENT_ID INT IDENTITY(1,1) NOT NULL,
    USER_ID  INT NOT NULL,
    LOGIN_AT DATETIME NOT NULL CONSTRAINT DF__USER_LOGIN_EVENTS__LOGIN_AT DEFAULT (GETDATE()),
    CONSTRAINT PK_USER_LOGIN_EVENTS PRIMARY KEY CLUSTERED (EVENT_ID)
);

CREATE NONCLUSTERED INDEX IX_USER_LOGIN_EVENTS_LOGIN_AT
    ON GUARDIAN.USER_LOGIN_EVENTS (LOGIN_AT);

CREATE NONCLUSTERED INDEX IX_USER_LOGIN_EVENTS_USER_LOGIN_AT
    ON GUARDIAN.USER_LOGIN_EVENTS (USER_ID, LOGIN_AT);
