-- DROP SCHEMA GUARDIAN;

CREATE SCHEMA GUARDIAN;
-- [GUARDIAN-DEV].GUARDIAN.ATTACHMENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ATTACHMENTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ATTACHMENTS (
	ATTACHMENT_ID int IDENTITY(1,1) NOT NULL,
	REQUEST_ID int NOT NULL,
	FILE_NAME varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ATTACHMENT varbinary(MAX) NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	COMPANY_ID int NULL,
	CONSTRAINT PK_ATTACHMENTS PRIMARY KEY (ATTACHMENT_ID)
);
 CREATE NONCLUSTERED INDEX IX_ATTACHMENTS_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.ATTACHMENTS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.AUDIT_LOG definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.AUDIT_LOG;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.AUDIT_LOG (
	ENTRY_ID bigint IDENTITY(1,1) NOT NULL,
	EVENT_TYPE nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ACTOR_USER_ID int NULL,
	ACTOR_ROLE_ID int NULL,
	TARGET_TYPE nvarchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TARGET_ID nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EVENT_DETAIL nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID int NULL,
	FIRST_TIME_FLAG bit NULL,
	DISCLAIMER_STATE bit NULL,
	CREATED_AT datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ENTRY_ID)
);
 CREATE NONCLUSTERED INDEX IX_AUDIT_LOG_COMPANY_CREATED ON GUARDIAN-DEV.GUARDIAN.AUDIT_LOG (  COMPANY_ID ASC  , CREATED_AT DESC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_AUDIT_LOG_EVENT_TYPE ON GUARDIAN-DEV.GUARDIAN.AUDIT_LOG (  EVENT_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_AUDIT_LOG_TARGET ON GUARDIAN-DEV.GUARDIAN.AUDIT_LOG (  TARGET_TYPE ASC  , TARGET_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.COMPANY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.COMPANY;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.COMPANY (
	COMPANY_ID int IDENTITY(1,1) NOT NULL,
	NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ADDRESS nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PHONE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATED_AT datetime DEFAULT getdate() NOT NULL,
	UPDATED_AT datetime DEFAULT getdate() NULL,
	CONSTRAINT PK__COMPANY__73B8DCFF3D624EE3 PRIMARY KEY (COMPANY_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FIELDS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FIELDS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FIELDS (
	FIELD_ID int IDENTITY(1000,1) NOT NULL,
	FIELD_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FIELD_TYPE_ID int NOT NULL,
	DISPLAY_FORMAT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HAS_LOOKUP bit DEFAULT 0 NOT NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	IS_ACTIVE bit DEFAULT 0 NOT NULL,
	IS_DELETED bit DEFAULT 0 NOT NULL,
	IS_REQUIRED bit DEFAULT 0 NOT NULL,
	IS_SENSITIVE bit DEFAULT 0 NOT NULL,
	CAN_SELECT_MULIPLE bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	FIELD_LOOKUP_DISPLAY_TYPE_ID int NULL,
	ORGANIZATION_ID int NULL,
	SORT_ORDER numeric(38,0) NULL,
	[OPTIONS] nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VALIDATION nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_FIELD PRIMARY KEY (FIELD_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FIELDS_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FIELDS_HISTORY;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FIELDS_HISTORY (
	FIELD_ID int NOT NULL,
	FIELD_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FIELD_TYPE_ID int NOT NULL,
	DISPLAY_FORMAT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HAS_LOOKUP bit NOT NULL,
	IS_PUBLIC bit NOT NULL,
	IS_ACTIVE bit NOT NULL,
	IS_DELETED bit NOT NULL,
	IS_REQUIRED bit NOT NULL,
	IS_SENSITIVE bit NOT NULL,
	CAN_SELECT_MULIPLE bit NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL,
	FIELD_LOOKUP_DISPLAY_TYPE_ID int NULL,
	ORGANIZATION_ID int NULL,
	SORT_ORDER numeric(38,0) NULL,
	[OPTIONS] nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VALIDATION nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);
 CREATE CLUSTERED INDEX ix_FIELDS_HISTORY ON GUARDIAN-DEV.GUARDIAN.FIELDS_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.FIELDS_LOOKUP definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FIELDS_LOOKUP;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FIELDS_LOOKUP (
	FIELD_LOOKUP_ID int IDENTITY(1000,1) NOT NULL,
	FIELD_ID int NOT NULL,
	LOOKUP_CODE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LOOKUP_DESCRIPTION varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_FIELDS_LOOKUP PRIMARY KEY (FIELD_LOOKUP_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FIELD_LOOKUP_DISPLAY_TYPE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FIELD_LOOKUP_DISPLAY_TYPE;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FIELD_LOOKUP_DISPLAY_TYPE (
	FIELD_LOOKUP_DISPLAY_TYPE_ID int IDENTITY(1,1) NOT NULL,
	FIELD_LOOKUP_DISPLAY_TYPE_DESCRIPTION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	CONSTRAINT PK_FIELD_LOOKUP_DISPLAY_TYPE PRIMARY KEY (FIELD_LOOKUP_DISPLAY_TYPE_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FIELD_TYPE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FIELD_TYPE;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FIELD_TYPE (
	FIELD_TYPE_ID int IDENTITY(1,1) NOT NULL,
	FIELD_TYPE_DESC varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	CONSTRAINT PK_FIELD_TYPE PRIMARY KEY (FIELD_TYPE_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FORMS_FIELDS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_FIELDS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_FIELDS (
	FORM_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	IS_REQUIRED bit DEFAULT 1 NOT NULL,
	SORT_ORDER int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	IS_PII bit DEFAULT 0 NOT NULL,
	IS_ENABLED bit DEFAULT 1 NOT NULL,
	IS_LOCKED_BY_JAFAR bit DEFAULT 0 NOT NULL,
	IS_READ_ONLY bit DEFAULT 0 NOT NULL
);


-- [GUARDIAN-DEV].GUARDIAN.FORMS_GROUPS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_GROUPS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_GROUPS (
	GROUP_ID int IDENTITY(1000,1) NOT NULL,
	ORGANIZATION_ID int NULL,
	GROUP_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GROUP_DESCRIPTION varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SORT_ORDER int NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_GROUP PRIMARY KEY (GROUP_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FORMS_GROUPS_FIELDS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_GROUPS_FIELDS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_GROUPS_FIELDS (
	GROUP_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	SORT_ORDER int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL
);


-- [GUARDIAN-DEV].GUARDIAN.FORMS_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_HISTORY;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_HISTORY (
	FORM_ID int NOT NULL,
	FORM_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FORM_DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ORGANIZATION_ID int NULL,
	IS_PUBLIC bit NOT NULL,
	IS_ACTIVE bit NOT NULL,
	IS_DELETED bit NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL,
	COMPANY_ID int NULL,
	WORKSPACE_ID int NULL,
	TEMPLATE_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STATUS nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	IS_INTERNAL bit NOT NULL,
	IS_EXTERNAL bit NOT NULL,
	NOTICE_SUBTYPE nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FRAUD_TYPE nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REQUIRES_MANAGER_APPROVAL bit NOT NULL,
	COMPLIANCE_DISCLAIMER_ENABLED bit NOT NULL,
	TITLE_FORMAT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NOTICE_CATEGORY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);
 CREATE CLUSTERED INDEX ix_FORMS_HISTORY ON GUARDIAN-DEV.GUARDIAN.FORMS_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_HISTORY;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_HISTORY (
	FORM_INSTANCE_ID int NOT NULL,
	FORM_ID int NOT NULL,
	ASSIGNED_ID int NULL,
	SUBMITTED_DATE datetime NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL,
	COMPANY_ID numeric(38,0) NULL,
	REQUEST_ID int NULL
);
 CREATE CLUSTERED INDEX ix_FORMS_INSTANCE_HISTORY ON GUARDIAN-DEV.GUARDIAN.FORMS_INSTANCE_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_VALUES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_VALUES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_VALUES (
	FORM_INSTANCE_VALUE_ID int IDENTITY(1000,1) NOT NULL,
	FORM_INSTANCE_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	VALUE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_FORMS_INSTANCE_VALUES PRIMARY KEY (FORM_INSTANCE_VALUE_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_VALUES_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_VALUES_HISTORY;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE_VALUES_HISTORY (
	FORM_INSTANCE_VALUE_ID int NOT NULL,
	FORM_INSTANCE_ID int NOT NULL,
	FIELD_ID int NOT NULL,
	VALUE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL
);
 CREATE CLUSTERED INDEX ix_FORMS_INSTANCE_VALUES_HISTORY ON GUARDIAN-DEV.GUARDIAN.FORMS_INSTANCE_VALUES_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.INVITES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.INVITES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.INVITES (
	INVITE_ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLE_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	TOKEN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXPIRES_AT datetime2 NOT NULL,
	USED_AT datetime2 NULL,
	CREATED_AT datetime2 DEFAULT sysdatetime() NOT NULL,
	CONSTRAINT PK__INVITES__F55A91112E684DE5 PRIMARY KEY (INVITE_ID),
	CONSTRAINT UQ__INVITES__05BE64EDCB9633D7 UNIQUE (TOKEN)
);


-- [GUARDIAN-DEV].GUARDIAN.JAFAR_PLATFORM_CONFIG definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.JAFAR_PLATFORM_CONFIG;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.JAFAR_PLATFORM_CONFIG (
	CONFIG_KEY nvarchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONFIG_VALUE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	UPDATED_BY int NULL,
	UPDATED_AT datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_JAFAR_PLATFORM_CONFIG PRIMARY KEY (CONFIG_KEY)
);


-- [GUARDIAN-DEV].GUARDIAN.MILESTONES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.MILESTONES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.MILESTONES (
	MILESTONE_ID int IDENTITY(1000,1) NOT NULL,
	EVENT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EVENT_DATE datetime DEFAULT getdate() NOT NULL,
	EVENT_USER_ID int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_MILESTONES PRIMARY KEY (MILESTONE_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.NOTIFICATIONS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTIFICATIONS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTIFICATIONS (
	NOTIFICATION_ID int IDENTITY(1,1) NOT NULL,
	USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	[TYPE] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TITLE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	MESSAGE varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	RELATED_ID int NULL,
	IS_READ bit DEFAULT 0 NOT NULL,
	CREATED_DATE datetime DEFAULT getdate() NOT NULL,
	READ_DATE datetime NULL,
	CONSTRAINT PK__NOTIFICA__83A4A446BA111651 PRIMARY KEY (NOTIFICATION_ID)
);
 CREATE NONCLUSTERED INDEX IX_NOTIFICATIONS_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.NOTIFICATIONS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTIFICATIONS_IS_READ ON GUARDIAN-DEV.GUARDIAN.NOTIFICATIONS (  IS_READ ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTIFICATIONS_USER_ID ON GUARDIAN-DEV.GUARDIAN.NOTIFICATIONS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS (
	ORGANIZATION_ID int IDENTITY(1000,1) NOT NULL,
	COMPANY_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WORK_SPACE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	CONSTRAINT PK_ORGANIZATIONS PRIMARY KEY (ORGANIZATION_ID)
);
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS WITH NOCHECK ADD CONSTRAINT CK_ORGANIZATIONS CHECK (([STATUS]='P' OR [STATUS]='I' OR [STATUS]='D' OR [STATUS]='A'));


-- [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS_HISTORY definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS_HISTORY;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ORGANIZATIONS_HISTORY (
	ORGANIZATION_ID int NOT NULL,
	COMPANY_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WORK_SPACE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SysStartTime datetime2 NOT NULL,
	SysEndTime datetime2 NOT NULL
);
 CREATE CLUSTERED INDEX ix_ORGANIZATIONS_HISTORY ON GUARDIAN-DEV.GUARDIAN.ORGANIZATIONS_HISTORY (  SysEndTime ASC  , SysStartTime ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.ROLES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ROLES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ROLES (
	ROLE_ID int IDENTITY(1,1) NOT NULL,
	NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DISPLAY_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NULL,
	UPDATE_DATE datetime DEFAULT getdate() NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	CONSTRAINT ROLES_PK PRIMARY KEY (ROLE_ID)
);
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.ROLES WITH NOCHECK ADD CONSTRAINT CK_ROLES CHECK (([STATUS]='P' OR [STATUS]='I' OR [STATUS]='D' OR [STATUS]='A'));


-- [GUARDIAN-DEV].GUARDIAN.SUBPOENA_LANGUAGE_TEMPLATES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.SUBPOENA_LANGUAGE_TEMPLATES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.SUBPOENA_LANGUAGE_TEMPLATES (
	LANGUAGE_TEMPLATE_ID int IDENTITY(1,1) NOT NULL,
	FRAUD_TYPE nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BASE_LANGUAGE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TOKENS_JSON nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CREATED_BY int NOT NULL,
	COMPANY_ID int NOT NULL,
	CREATED_AT datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATED_AT datetime2 NULL,
	CONSTRAINT PK_SUBPOENA_LANG_TEMPLATES PRIMARY KEY (LANGUAGE_TEMPLATE_ID),
	CONSTRAINT UQ_SUBPOENA_LANG_FRAUD_PER_COMPANY UNIQUE (COMPANY_ID,FRAUD_TYPE)
);


-- [GUARDIAN-DEV].GUARDIAN.TASKS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.TASKS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.TASKS (
	TASK_ID int IDENTITY(1000,1) NOT NULL,
	REQUEST_ID int NOT NULL,
	STATUS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ASSIGNED_USER_ID int NOT NULL,
	DESCRIPTION varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_TASKS PRIMARY KEY (TASK_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.TEST definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.TEST;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.TEST (
	ID int NULL,
	NAME varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);


-- [GUARDIAN-DEV].GUARDIAN.USERS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.USERS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.USERS (
	USER_ID int IDENTITY(1000,1) NOT NULL,
	FIRST_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LAST_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EMAIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PIN int NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	PASSWORD_HASH varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL_VALIDATED bit DEFAULT 0 NOT NULL,
	EMAIL_VALIDATION_TOKEN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PASSWORD_RESET_TOKEN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID int NULL,
	EMAIL_VALIDATION_CODE_PLAIN varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL_VALIDATION_TOKEN_EXPIRY datetime2 NULL,
	PASSWORD_RESET_TOKEN_EXPIRY datetime2 NULL,
	ACTIVE_WORKSPACE_ID int NULL,
	ACCOUNT_CREATOR_INVITE_COMPLETED bit DEFAULT 0 NOT NULL,
	NOTIFICATION_PREFERENCES nvarchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
	CONSTRAINT UQ_USERS_EMAIL_COMPANY UNIQUE (EMAIL,COMPANY_ID)
);
 CREATE NONCLUSTERED INDEX IX_USERS_EMAIL_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.USERS (  EMAIL ASC  , COMPANY_ID ASC  )  
	 INCLUDE ( FIRST_NAME , LAST_NAME , STATUS , USER_ID ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.USERS WITH NOCHECK ADD CONSTRAINT CK_USERS CHECK (([STATUS]='P' OR [STATUS]='I' OR [STATUS]='D' OR [STATUS]='A'));


-- [GUARDIAN-DEV].GUARDIAN.USER_LOGIN_EVENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.USER_LOGIN_EVENTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.USER_LOGIN_EVENTS (
	EVENT_ID int IDENTITY(1,1) NOT NULL,
	USER_ID int NOT NULL,
	LOGIN_AT datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_USER_LOGIN_EVENTS PRIMARY KEY (EVENT_ID)
);
 CREATE NONCLUSTERED INDEX IX_USER_LOGIN_EVENTS_LOGIN_AT ON GUARDIAN-DEV.GUARDIAN.USER_LOGIN_EVENTS (  LOGIN_AT ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_USER_LOGIN_EVENTS_USER_LOGIN_AT ON GUARDIAN-DEV.GUARDIAN.USER_LOGIN_EVENTS (  USER_ID ASC  , LOGIN_AT ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.USER_ROLES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.USER_ROLES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.USER_ROLES (
	USER_ROLE_ID int IDENTITY(1,1) NOT NULL,
	USER_ID int NOT NULL,
	ROLE_ID int NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NULL,
	UPDATE_DATE datetime DEFAULT getdate() NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NOT NULL,
	CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ROLE_ID)
);
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.USER_ROLES WITH NOCHECK ADD CONSTRAINT CK_USER_ROL CHECK (([STATUS]='P' OR [STATUS]='I' OR [STATUS]='D' OR [STATUS]='A'));


-- [GUARDIAN-DEV].GUARDIAN.WORKSPACES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.WORKSPACES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.WORKSPACES (
	WORKSPACE_ID int IDENTITY(1,1) NOT NULL,
	WORKSPACE_NAME nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DESCRIPTION nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID int NOT NULL,
	IS_ACTIVE bit DEFAULT 1 NOT NULL,
	IS_DEFAULT bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	CONSTRAINT PK__WORKSPAC__549E2259957B43B4 PRIMARY KEY (WORKSPACE_ID),
	CONSTRAINT UQ_WORKSPACES_COMPANY_NAME UNIQUE (COMPANY_ID,WORKSPACE_NAME)
);
 CREATE NONCLUSTERED INDEX IX_WORKSPACES_COMPANY_ACTIVE ON GUARDIAN-DEV.GUARDIAN.WORKSPACES (  COMPANY_ID ASC  , IS_ACTIVE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.COMPANY_INFO definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.COMPANY_INFO;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.COMPANY_INFO (
	COMPANY_INFO_ID int IDENTITY(1,1) NOT NULL,
	COMPANY_ID int NOT NULL,
	USER_ID int NOT NULL,
	WORKSPACE_NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROLE] nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEAM_SIZE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_SIZE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATED_AT datetime DEFAULT getdate() NOT NULL,
	UPDATED_AT datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK__COMPANY___2099A60865741D46 PRIMARY KEY (COMPANY_INFO_ID),
	CONSTRAINT FK_COMPANY_INFO_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID),
	CONSTRAINT FK_COMPANY_INFO_USERS FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.FORMS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS (
	FORM_ID int IDENTITY(1000,1) NOT NULL,
	FORM_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FORM_DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ORGANIZATION_ID int NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	IS_ACTIVE bit DEFAULT 0 NOT NULL,
	IS_DELETED bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	COMPANY_ID int NULL,
	WORKSPACE_ID int NULL,
	TEMPLATE_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'request' NOT NULL,
	STATUS nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'draft' NOT NULL,
	IS_INTERNAL bit DEFAULT 1 NOT NULL,
	IS_EXTERNAL bit DEFAULT 1 NOT NULL,
	NOTICE_SUBTYPE nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FRAUD_TYPE nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REQUIRES_MANAGER_APPROVAL bit DEFAULT 0 NOT NULL,
	COMPLIANCE_DISCLAIMER_ENABLED bit DEFAULT 0 NOT NULL,
	TITLE_FORMAT nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NOTICE_CATEGORY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_FORMS PRIMARY KEY (FORM_ID),
	CONSTRAINT FK_FORMS_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.WORKSPACES(WORKSPACE_ID),
	CONSTRAINT FK__FORMS__COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID)
);
 CREATE NONCLUSTERED INDEX IX_FORMS_WORKSPACE ON GUARDIAN-DEV.GUARDIAN.FORMS (  WORKSPACE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.FORMS WITH NOCHECK ADD CONSTRAINT CK_FORMS_TEMPLATE_TYPE CHECK (([TEMPLATE_TYPE]='request' OR [TEMPLATE_TYPE]='notice'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.FORMS WITH NOCHECK ADD CONSTRAINT CK_FORMS_STATUS CHECK (([STATUS]='inactive' OR [STATUS]='active' OR [STATUS]='draft'));


-- [GUARDIAN-DEV].GUARDIAN.MY_NOTICES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.MY_NOTICES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.MY_NOTICES (
	NOTICE_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_TITLE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SENSITIVITY_CLASSIFICATION nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BUTTON_STATUS nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DISTRIBUTION_TYPE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NOTICE_BODY nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_DATE datetime2 NULL,
	COMPANY_ID int NULL,
	TEMPLATE_FORM_ID int NULL,
	NOTICE_STATUS nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'DRAFT' NOT NULL,
	SUBMITTED_BY int NULL,
	SUBMITTED_AT datetime2 NULL,
	APPROVED_BY int NULL,
	APPROVED_AT datetime2 NULL,
	REJECTED_BY int NULL,
	REJECTED_AT datetime2 NULL,
	REJECTION_REASON nvarchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SENT_AT datetime2 NULL,
	DISCLAIMER_STATE bit NULL,
	FIRST_TIME_RECIPIENT_FLAG bit NULL,
	SUBPOENA_RIDER_ID int NULL,
	ATTACHED_SUBPOENA_ATTACHMENT_ID int NULL,
	TEMPLATE_VALUES_JSON nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_MY_NOTICES PRIMARY KEY (NOTICE_ID),
	CONSTRAINT FK_MY_NOTICES_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID),
	CONSTRAINT FK_MY_NOTICES_CREATE_USER FOREIGN KEY (CREATE_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_MY_NOTICES_TEMPLATE_FORM FOREIGN KEY (TEMPLATE_FORM_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.FORMS(FORM_ID),
	CONSTRAINT FK_MY_NOTICES_UPDATE_USER FOREIGN KEY (UPDATE_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_MY_NOTICES_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.MY_NOTICES (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_MY_NOTICES_CREATE_USER ON GUARDIAN-DEV.GUARDIAN.MY_NOTICES (  CREATE_USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_MY_NOTICES_NOTICE_STATUS ON GUARDIAN-DEV.GUARDIAN.MY_NOTICES (  NOTICE_STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_MY_NOTICES_STATUS ON GUARDIAN-DEV.GUARDIAN.MY_NOTICES (  BUTTON_STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.MY_NOTICE_RECIPIENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.MY_NOTICE_RECIPIENTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.MY_NOTICE_RECIPIENTS (
	NOTICE_RECIPIENT_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	USER_ID int NOT NULL,
	CONSTRAINT PK_MY_NOTICE_RECIPIENTS PRIMARY KEY (NOTICE_RECIPIENT_ID),
	CONSTRAINT UQ_MY_NOTICE_RECIPIENTS UNIQUE (NOTICE_ID,USER_ID),
	CONSTRAINT FK_MY_NOTICE_RECIPIENTS_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.MY_NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_MY_NOTICE_RECIPIENTS_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID) ON DELETE CASCADE
);
 CREATE NONCLUSTERED INDEX IX_MY_NOTICE_RECIP_NOTICE ON GUARDIAN-DEV.GUARDIAN.MY_NOTICE_RECIPIENTS (  NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_MY_NOTICE_RECIP_USER ON GUARDIAN-DEV.GUARDIAN.MY_NOTICE_RECIPIENTS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.NOTICES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICES (
	NOTICE_ID int IDENTITY(1,1) NOT NULL,
	TITLE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONTENT nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NOTICE_TYPE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STATUS nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'DRAFT' NOT NULL,
	ISSUED_BY_USER_ID int NOT NULL,
	ISSUE_DATE datetime2 NULL,
	COMPANY_ID int NOT NULL,
	FORM_TEMPLATE_ID int NULL,
	CANCELLATION_REASON nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_ACTIVE bit DEFAULT 1 NOT NULL,
	IS_DELETED bit DEFAULT 0 NOT NULL,
	CREATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	PRIORITY_LEVEL nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'MEDIUM' NOT NULL,
	DUE_DATE datetime2 NULL,
	WORKSPACE_ID int NULL,
	CONSTRAINT PK_NOTICES PRIMARY KEY (NOTICE_ID),
	CONSTRAINT FK_NOTICES_FORM_TEMPLATE FOREIGN KEY (FORM_TEMPLATE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.FORMS(FORM_ID),
	CONSTRAINT FK_NOTICES_ISSUED_BY_USER FOREIGN KEY (ISSUED_BY_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_NOTICES_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.WORKSPACES(WORKSPACE_ID)
);
 CREATE NONCLUSTERED INDEX IX_NOTICES_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.NOTICES (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_DUE_DATE ON GUARDIAN-DEV.GUARDIAN.NOTICES (  DUE_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_ISSUED_BY_USER_ID ON GUARDIAN-DEV.GUARDIAN.NOTICES (  ISSUED_BY_USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_ISSUE_DATE ON GUARDIAN-DEV.GUARDIAN.NOTICES (  ISSUE_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_PRIORITY_DUE_DATE ON GUARDIAN-DEV.GUARDIAN.NOTICES (  PRIORITY_LEVEL ASC  , DUE_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_PRIORITY_LEVEL ON GUARDIAN-DEV.GUARDIAN.NOTICES (  PRIORITY_LEVEL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_STATUS ON GUARDIAN-DEV.GUARDIAN.NOTICES (  STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICES_WORKSPACE ON GUARDIAN-DEV.GUARDIAN.NOTICES (  WORKSPACE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICES WITH NOCHECK ADD CONSTRAINT CHK_NOTICES_PRIORITY_LEVEL CHECK (([PRIORITY_LEVEL]='LOW' OR [PRIORITY_LEVEL]='MEDIUM' OR [PRIORITY_LEVEL]='HIGH'));


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS (
	CONTACT_GROUP_ID int IDENTITY(1,1) NOT NULL,
	GROUP_NAME nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GROUP_DESCRIPTION nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GROUP_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'CUSTOM' NOT NULL,
	COMPANY_ID int NOT NULL,
	CREATED_BY_USER_ID int NOT NULL,
	GROUP_STATUS nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ACTIVE' NOT NULL,
	IS_PUBLIC bit DEFAULT 0 NOT NULL,
	IS_SYSTEM_GROUP bit DEFAULT 0 NOT NULL,
	AUTO_UPDATE bit DEFAULT 0 NOT NULL,
	AUTO_UPDATE_CRITERIA nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MEMBER_COUNT int DEFAULT 0 NOT NULL,
	LAST_USED_DATE datetime2 NULL,
	USAGE_COUNT int DEFAULT 0 NOT NULL,
	ACCESS_LEVEL nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ADMIN_ONLY' NOT NULL,
	NOTIFICATION_PREFERENCES nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GROUP_COLOR nvarchar(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GROUP_ICON nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORT_ORDER int DEFAULT 0 NOT NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CONSTRAINT PK_NOTICE_CONTACT_GROUPS PRIMARY KEY (CONTACT_GROUP_ID),
	CONSTRAINT UQ_CONTACT_GROUPS_NAME_COMPANY UNIQUE (COMPANY_ID,GROUP_NAME),
	CONSTRAINT FK_CONTACT_GROUPS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID) ON DELETE CASCADE,
	CONSTRAINT FK_CONTACT_GROUPS_CREATOR FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_CONTACT_GROUPS_AUTO ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUPS (  COMPANY_ID ASC  , AUTO_UPDATE ASC  , GROUP_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_CONTACT_GROUPS_COMPANY ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUPS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_CONTACT_GROUPS_CREATOR ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUPS (  CREATED_BY_USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_CONTACT_GROUPS_STATUS ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUPS (  GROUP_STATUS ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_CONTACT_GROUPS_TYPE ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUPS (  GROUP_TYPE ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_CONTACT_GROUPS_USAGE ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUPS (  COMPANY_ID ASC  , LAST_USED_DATE ASC  , USAGE_COUNT ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS WITH NOCHECK ADD CONSTRAINT CHK_CONTACT_GROUPS_TYPE CHECK (([GROUP_TYPE]='SHIFT' OR [GROUP_TYPE]='SKILL' OR [GROUP_TYPE]='TEAM' OR [GROUP_TYPE]='EMERGENCY' OR [GROUP_TYPE]='LOCATION' OR [GROUP_TYPE]='PROJECT' OR [GROUP_TYPE]='ROLE' OR [GROUP_TYPE]='DEPARTMENT' OR [GROUP_TYPE]='CUSTOM'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS WITH NOCHECK ADD CONSTRAINT CHK_CONTACT_GROUPS_STATUS CHECK (([GROUP_STATUS]='ARCHIVED' OR [GROUP_STATUS]='INACTIVE' OR [GROUP_STATUS]='ACTIVE'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS WITH NOCHECK ADD CONSTRAINT CHK_CONTACT_GROUPS_ACCESS CHECK (([ACCESS_LEVEL]='CREATOR_ONLY' OR [ACCESS_LEVEL]='PUBLIC' OR [ACCESS_LEVEL]='MANAGER' OR [ACCESS_LEVEL]='ADMIN_ONLY'));


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS (
	GROUP_MEMBER_ID int IDENTITY(1,1) NOT NULL,
	CONTACT_GROUP_ID int NOT NULL,
	USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	MEMBER_TYPE nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'MEMBER' NOT NULL,
	MEMBER_STATUS nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ACTIVE' NOT NULL,
	ADDED_BY_USER_ID int NOT NULL,
	ADDED_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	NOTIFICATION_PREFERENCE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'DEFAULT' NULL,
	IS_AUTO_ADDED bit DEFAULT 0 NOT NULL,
	AUTO_ADD_REASON nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LAST_NOTIFICATION_DATE datetime2 NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_CONTACT_GROUP_MEMBERS PRIMARY KEY (GROUP_MEMBER_ID),
	CONSTRAINT UQ_GROUP_MEMBERS UNIQUE (CONTACT_GROUP_ID,USER_ID),
	CONSTRAINT FK_GROUP_MEMBERS_ADDER FOREIGN KEY (ADDED_BY_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_GROUP_MEMBERS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID),
	CONSTRAINT FK_GROUP_MEMBERS_GROUP FOREIGN KEY (CONTACT_GROUP_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUPS(CONTACT_GROUP_ID) ON DELETE CASCADE,
	CONSTRAINT FK_GROUP_MEMBERS_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID) ON DELETE CASCADE
);
 CREATE NONCLUSTERED INDEX IX_GROUP_MEMBERS_COMPANY ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_GROUP_MEMBERS_GROUP ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS (  CONTACT_GROUP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_GROUP_MEMBERS_STATUS ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS (  MEMBER_STATUS ASC  , CONTACT_GROUP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_GROUP_MEMBERS_TYPE ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS (  MEMBER_TYPE ASC  , CONTACT_GROUP_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_GROUP_MEMBERS_USER ON GUARDIAN-DEV.GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS WITH NOCHECK ADD CONSTRAINT CHK_GROUP_MEMBERS_TYPE CHECK (([MEMBER_TYPE]='VIEWER' OR [MEMBER_TYPE]='ADMIN' OR [MEMBER_TYPE]='MANAGER' OR [MEMBER_TYPE]='MEMBER'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS WITH NOCHECK ADD CONSTRAINT CHK_GROUP_MEMBERS_STATUS CHECK (([MEMBER_STATUS]='REMOVED' OR [MEMBER_STATUS]='PENDING' OR [MEMBER_STATUS]='INACTIVE' OR [MEMBER_STATUS]='ACTIVE'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_CONTACT_GROUP_MEMBERS WITH NOCHECK ADD CONSTRAINT CHK_GROUP_MEMBERS_NOTIFICATION CHECK (([NOTIFICATION_PREFERENCE]='DISABLED' OR [NOTIFICATION_PREFERENCE]='IN_APP_ONLY' OR [NOTIFICATION_PREFERENCE]='EMAIL_ONLY' OR [NOTIFICATION_PREFERENCE]='DEFAULT'));


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_GROUP_TEMPLATES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_GROUP_TEMPLATES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_GROUP_TEMPLATES (
	GROUP_TEMPLATE_ID int IDENTITY(1,1) NOT NULL,
	TEMPLATE_NAME nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TEMPLATE_DESCRIPTION nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID int NOT NULL,
	CREATED_BY_USER_ID int NOT NULL,
	TEMPLATE_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'DISTRIBUTION' NOT NULL,
	GROUP_COMBINATION nvarchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ESCALATION_RULES nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRIORITY_OVERRIDE nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_EMERGENCY_TEMPLATE bit DEFAULT 0 NOT NULL,
	USAGE_COUNT int DEFAULT 0 NOT NULL,
	LAST_USED_DATE datetime2 NULL,
	IS_ACTIVE bit DEFAULT 1 NOT NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_NOTICE_GROUP_TEMPLATES PRIMARY KEY (GROUP_TEMPLATE_ID),
	CONSTRAINT UQ_GROUP_TEMPLATES_NAME_COMPANY UNIQUE (COMPANY_ID,TEMPLATE_NAME),
	CONSTRAINT FK_GROUP_TEMPLATES_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID) ON DELETE CASCADE,
	CONSTRAINT FK_GROUP_TEMPLATES_CREATOR FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_GROUP_TEMPLATES_COMPANY ON GUARDIAN-DEV.GUARDIAN.NOTICE_GROUP_TEMPLATES (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_GROUP_TEMPLATES_EMERGENCY ON GUARDIAN-DEV.GUARDIAN.NOTICE_GROUP_TEMPLATES (  IS_EMERGENCY_TEMPLATE ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_GROUP_TEMPLATES_TYPE ON GUARDIAN-DEV.GUARDIAN.NOTICE_GROUP_TEMPLATES (  TEMPLATE_TYPE ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_GROUP_TEMPLATES WITH NOCHECK ADD CONSTRAINT CHK_GROUP_TEMPLATES_TYPE CHECK (([TEMPLATE_TYPE]='WORKFLOW' OR [TEMPLATE_TYPE]='ANNOUNCEMENT' OR [TEMPLATE_TYPE]='EMERGENCY' OR [TEMPLATE_TYPE]='ESCALATION' OR [TEMPLATE_TYPE]='DISTRIBUTION'));


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS (
	NOTICE_METRIC_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	VIEW_START_TIME datetime2 DEFAULT getutcdate() NOT NULL,
	VIEW_END_TIME datetime2 NULL,
	VIEW_DURATION_SECONDS int NULL,
	SCROLL_PERCENTAGE decimal(5,2) DEFAULT 0 NULL,
	INTERACTION_COUNT int DEFAULT 0 NOT NULL,
	DEVICE_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFERRER_SOURCE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_COMPLETED_VIEW bit DEFAULT 0 NOT NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_NOTICE_METRICS PRIMARY KEY (NOTICE_METRIC_ID),
	CONSTRAINT FK_NOTICE_METRICS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_METRICS_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_METRICS_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID) ON DELETE CASCADE
);
 CREATE NONCLUSTERED INDEX IX_NOTICE_METRICS_ANALYTICS ON GUARDIAN-DEV.GUARDIAN.NOTICE_METRICS (  COMPANY_ID ASC  , VIEW_START_TIME ASC  , IS_COMPLETED_VIEW ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_METRICS_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_METRICS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_METRICS_COMPANY_NOTICE ON GUARDIAN-DEV.GUARDIAN.NOTICE_METRICS (  COMPANY_ID ASC  , NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_METRICS_NOTICE_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_METRICS (  NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_METRICS_USER_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_METRICS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_METRICS_VIEW_START_TIME ON GUARDIAN-DEV.GUARDIAN.NOTICE_METRICS (  VIEW_START_TIME ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_METRICS_SCROLL_PERCENTAGE CHECK (([SCROLL_PERCENTAGE]>=(0) AND [SCROLL_PERCENTAGE]<=(100)));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_METRICS_VIEW_DURATION CHECK (([VIEW_DURATION_SECONDS]>=(0)));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_METRICS_DEVICE_TYPE CHECK (([DEVICE_TYPE]=NULL OR [DEVICE_TYPE]='TABLET' OR [DEVICE_TYPE]='MOBILE' OR [DEVICE_TYPE]='DESKTOP'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_METRICS WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_METRICS_REFERRER CHECK (([REFERRER_SOURCE]=NULL OR [REFERRER_SOURCE]='NOTIFICATION' OR [REFERRER_SOURCE]='EMAIL' OR [REFERRER_SOURCE]='DIRECT_LINK' OR [REFERRER_SOURCE]='ALL_NOTICES' OR [REFERRER_SOURCE]='MY_NOTICES'));


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_READ_STATUS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_READ_STATUS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_READ_STATUS (
	NOTICE_READ_STATUS_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	USER_ID int NOT NULL,
	READ_DATE datetime2 DEFAULT getdate() NOT NULL,
	COMPANY_ID int NOT NULL,
	CREATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_NOTICE_READ_STATUS PRIMARY KEY (NOTICE_READ_STATUS_ID),
	CONSTRAINT UQ_NOTICE_READ_STATUS_UNIQUE UNIQUE (NOTICE_ID,USER_ID),
	CONSTRAINT FK_NOTICE_READ_STATUS_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_READ_STATUS_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_NOTICE_READ_STATUS_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_READ_STATUS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_READ_STATUS_USER_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_READ_STATUS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_RECIPIENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RECIPIENTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RECIPIENTS (
	NOTICE_RECIPIENT_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	RECIPIENT_USER_ID int NOT NULL,
	RECIPIENT_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'USER' NOT NULL,
	COMPANY_ID int NOT NULL,
	CREATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	CREATE_USER_ID int NULL,
	CONSTRAINT PK_NOTICE_RECIPIENTS PRIMARY KEY (NOTICE_RECIPIENT_ID),
	CONSTRAINT UQ_NOTICE_RECIPIENTS_UNIQUE UNIQUE (NOTICE_ID,RECIPIENT_USER_ID),
	CONSTRAINT FK_NOTICE_RECIPIENTS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID),
	CONSTRAINT FK_NOTICE_RECIPIENTS_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_RECIPIENTS_USER FOREIGN KEY (RECIPIENT_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_NOTICE_RECIPIENTS_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_RECIPIENTS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RECIPIENTS_NOTICE_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_RECIPIENTS (  NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RECIPIENTS_RECIPIENT_USER_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_RECIPIENTS (  RECIPIENT_USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES (
	NOTICE_RESPONSE_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	RESPONSE_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ACKNOWLEDGED' NOT NULL,
	RESPONSE_MESSAGE nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESPONSE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	RESPONSE_STATUS nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ACTIVE' NOT NULL,
	REQUIRES_FOLLOWUP bit DEFAULT 0 NOT NULL,
	FOLLOWUP_PRIORITY nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FOLLOWUP_ASSIGNED_TO int NULL,
	FOLLOWUP_COMPLETED_DATE datetime2 NULL,
	FOLLOWUP_NOTES nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NOTIFICATION_SENT bit DEFAULT 0 NOT NULL,
	IS_ANONYMOUS bit DEFAULT 0 NOT NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CONSTRAINT PK_NOTICE_RESPONSES PRIMARY KEY (NOTICE_RESPONSE_ID),
	CONSTRAINT UQ_NOTICE_RESPONSES_USER_NOTICE UNIQUE (NOTICE_ID,USER_ID,RESPONSE_STATUS),
	CONSTRAINT FK_NOTICE_RESPONSES_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_RESPONSES_FOLLOWUP_USER FOREIGN KEY (FOLLOWUP_ASSIGNED_TO) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_NOTICE_RESPONSES_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_RESPONSES_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID) ON DELETE CASCADE
);
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_ANALYTICS ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  COMPANY_ID ASC  , RESPONSE_DATE ASC  , RESPONSE_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_COMPANY_NOTICE ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  COMPANY_ID ASC  , NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_FOLLOWUP ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  REQUIRES_FOLLOWUP ASC  , FOLLOWUP_COMPLETED_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_NOTICE_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_RESPONSE_DATE ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  RESPONSE_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_TYPE_STATUS ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  RESPONSE_TYPE ASC  , RESPONSE_STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_NOTICE_RESPONSES_USER_ID ON GUARDIAN-DEV.GUARDIAN.NOTICE_RESPONSES (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_RESPONSES_TYPE CHECK (([RESPONSE_TYPE]='PARTIALLY_COMPLETED' OR [RESPONSE_TYPE]='NEEDS_EXTENSION' OR [RESPONSE_TYPE]='CANNOT_COMPLY' OR [RESPONSE_TYPE]='REQUIRES_CLARIFICATION' OR [RESPONSE_TYPE]='COMPLETED' OR [RESPONSE_TYPE]='UNDERSTOOD' OR [RESPONSE_TYPE]='ACKNOWLEDGED'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_RESPONSES_STATUS CHECK (([RESPONSE_STATUS]='SUPERSEDED' OR [RESPONSE_STATUS]='WITHDRAWN' OR [RESPONSE_STATUS]='ACTIVE'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_RESPONSES_FOLLOWUP_PRIORITY CHECK (([FOLLOWUP_PRIORITY]=NULL OR [FOLLOWUP_PRIORITY]='LOW' OR [FOLLOWUP_PRIORITY]='MEDIUM' OR [FOLLOWUP_PRIORITY]='HIGH'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_RESPONSES_MESSAGE_LENGTH CHECK ((len([RESPONSE_MESSAGE])<=(1000)));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_RESPONSES WITH NOCHECK ADD CONSTRAINT CHK_NOTICE_RESPONSES_FOLLOWUP_LOGIC CHECK (([REQUIRES_FOLLOWUP]=(0) AND [FOLLOWUP_PRIORITY] IS NULL AND [FOLLOWUP_ASSIGNED_TO] IS NULL OR [REQUIRES_FOLLOWUP]=(1) AND [FOLLOWUP_PRIORITY] IS NOT NULL));


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATES (
	NOTICE_UPDATE_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	PARENT_UPDATE_ID int NULL,
	THREAD_LEVEL int DEFAULT 0 NOT NULL,
	UPDATE_TYPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'UPDATE' NOT NULL,
	UPDATE_TITLE nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UPDATE_CONTENT nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONTENT_TYPE nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'TEXT' NOT NULL,
	AUTHOR_USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	UPDATE_STATUS nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ACTIVE' NOT NULL,
	IS_PINNED bit DEFAULT 0 NOT NULL,
	REQUIRES_ACKNOWLEDGMENT bit DEFAULT 0 NOT NULL,
	PRIORITY_LEVEL nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'NORMAL' NOT NULL,
	VISIBILITY_SCOPE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'ALL_RECIPIENTS' NOT NULL,
	TAGGED_USERS nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MENTIONED_USERS nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UPDATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	EDIT_DATE datetime2 NULL,
	EDITED_BY_USER_ID int NULL,
	EDIT_REASON nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NOTIFICATION_SENT bit DEFAULT 0 NOT NULL,
	VIEW_COUNT int DEFAULT 0 NOT NULL,
	REACTION_COUNT int DEFAULT 0 NOT NULL,
	REPLY_COUNT int DEFAULT 0 NOT NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	UPDATE_USER_ID int NULL,
	CONSTRAINT PK_NOTICE_UPDATES PRIMARY KEY (NOTICE_UPDATE_ID),
	CONSTRAINT FK_NOTICE_UPDATES_AUTHOR FOREIGN KEY (AUTHOR_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_NOTICE_UPDATES_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_UPDATES_EDITOR FOREIGN KEY (EDITED_BY_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_NOTICE_UPDATES_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NOTICE_UPDATES_PARENT FOREIGN KEY (PARENT_UPDATE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATES(NOTICE_UPDATE_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATE_ACKNOWLEDGMENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATE_ACKNOWLEDGMENTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATE_ACKNOWLEDGMENTS (
	ACKNOWLEDGMENT_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_UPDATE_ID int NOT NULL,
	USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	ACKNOWLEDGED_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	ACKNOWLEDGMENT_TYPE nvarchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'read' NOT NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_NOTICE_UPDATE_ACKNOWLEDGMENTS PRIMARY KEY (ACKNOWLEDGMENT_ID),
	CONSTRAINT UQ_UPDATE_ACKNOWLEDGMENTS UNIQUE (NOTICE_UPDATE_ID,USER_ID),
	CONSTRAINT FK_UPDATE_ACK_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID),
	CONSTRAINT FK_UPDATE_ACK_UPDATE FOREIGN KEY (NOTICE_UPDATE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATES(NOTICE_UPDATE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_UPDATE_ACK_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_UPDATE_ACK_UPDATE ON GUARDIAN-DEV.GUARDIAN.NOTICE_UPDATE_ACKNOWLEDGMENTS (  NOTICE_UPDATE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_UPDATE_ACK_USER ON GUARDIAN-DEV.GUARDIAN.NOTICE_UPDATE_ACKNOWLEDGMENTS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.NOTICE_UPDATE_ACKNOWLEDGMENTS WITH NOCHECK ADD CONSTRAINT CHK_UPDATE_ACK_TYPE CHECK (([ACKNOWLEDGMENT_TYPE]='dismissed' OR [ACKNOWLEDGMENT_TYPE]='noted' OR [ACKNOWLEDGMENT_TYPE]='agreed' OR [ACKNOWLEDGMENT_TYPE]='understood' OR [ACKNOWLEDGMENT_TYPE]='read'));


-- [GUARDIAN-DEV].GUARDIAN.RECIPIENT_VERIFICATIONS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.RECIPIENT_VERIFICATIONS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.RECIPIENT_VERIFICATIONS (
	VERIFICATION_ID int IDENTITY(1,1) NOT NULL,
	RECIPIENT_USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	VERIFIED_STATUS nvarchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'FIRST_TIME' NOT NULL,
	VERIFIED_AT datetime2 NULL,
	FIRST_NOTICE_ID int NULL,
	CONSTRAINT PK_RECIPIENT_VERIFICATIONS PRIMARY KEY (VERIFICATION_ID),
	CONSTRAINT UQ_RECIPIENT_VERIFICATIONS_USER_COMPANY UNIQUE (RECIPIENT_USER_ID,COMPANY_ID),
	CONSTRAINT FK_RV_FIRST_NOTICE FOREIGN KEY (FIRST_NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.MY_NOTICES(NOTICE_ID),
	CONSTRAINT FK_RV_USER FOREIGN KEY (RECIPIENT_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_RV_STATUS ON GUARDIAN-DEV.GUARDIAN.RECIPIENT_VERIFICATIONS (  COMPANY_ID ASC  , VERIFIED_STATUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.REQUESTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.REQUESTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.REQUESTS (
	REQUEST_ID int IDENTITY(1,1) NOT NULL,
	REQUEST_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXTERNAL_USER char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'N' NULL,
	SUBMITTED_DATE datetime DEFAULT getdate() NOT NULL,
	REQUESTOR_ID int NULL,
	ASSIGNED_ID int NULL,
	STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'P' NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	TRACKINGID AS ((('REQ-'+format([SUBMITTED_DATE],'yyyy'))+'-')+right('000'+CONVERT([varchar](3),[REQUEST_ID]),(3))),
	ABBREVIATION varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPANY_ID numeric(38,0) NULL,
	REQUEST_DESCRIPTION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FORM_ID int NULL,
	RESULTS_DESRIPTION nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESULTS_DESCRIPTION nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRIORITY_LEVEL nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'Standard' NOT NULL,
	WORKSPACE_ID int NULL,
	CANCELLATION_REASON nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CANCELLED_DATE datetime NULL,
	CANCELLED_BY int NULL,
	ANALYST_ID int NULL,
	INVESTIGATOR_ID int NULL,
	CONSTRAINT PK_REQUESTS PRIMARY KEY (REQUEST_ID),
	CONSTRAINT FK_REQUESTS_CANCELLED_BY FOREIGN KEY (CANCELLED_BY) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_REQUESTS_FORM_ID FOREIGN KEY (FORM_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.FORMS(FORM_ID),
	CONSTRAINT FK_REQUESTS_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.WORKSPACES(WORKSPACE_ID)
);
 CREATE NONCLUSTERED INDEX IX_REQUESTS_CANCELLED_BY ON GUARDIAN-DEV.GUARDIAN.REQUESTS (  CANCELLED_BY ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_REQUESTS_PRIORITY_LEVEL ON GUARDIAN-DEV.GUARDIAN.REQUESTS (  PRIORITY_LEVEL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_REQUESTS_STATUS_CANCELLED_DATE ON GUARDIAN-DEV.GUARDIAN.REQUESTS (  STATUS ASC  , CANCELLED_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_REQUESTS_WORKSPACE ON GUARDIAN-DEV.GUARDIAN.REQUESTS (  WORKSPACE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.REQUESTS WITH NOCHECK ADD CONSTRAINT CHK_REQUESTS_PRIORITY_LEVEL CHECK (([PRIORITY_LEVEL]='High' OR [PRIORITY_LEVEL]='Standard' OR [PRIORITY_LEVEL]='Low'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.REQUESTS WITH NOCHECK ADD CONSTRAINT CK_REQUEST_EXTERNAL_USER CHECK (([EXTERNAL_USER]='Y' OR [EXTERNAL_USER]='N'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.REQUESTS WITH NOCHECK ADD CONSTRAINT CK_REQUEST_STATUS CHECK (([STATUS]='R' OR [STATUS]='H' OR [STATUS]='X' OR [STATUS]='I' OR [STATUS]='D' OR [STATUS]='A' OR [STATUS]='P'));
ALTER TABLE [GUARDIAN-DEV].GUARDIAN.REQUESTS WITH NOCHECK ADD CONSTRAINT CHK_REQUESTS_CANCELLATION_FIELDS CHECK (([STATUS]='X' AND [CANCELLED_DATE] IS NOT NULL AND [CANCELLED_BY] IS NOT NULL OR [STATUS]<>'X' AND [CANCELLED_DATE] IS NULL AND [CANCELLED_BY] IS NULL AND [CANCELLATION_REASON] IS NULL));


-- [GUARDIAN-DEV].GUARDIAN.RESPONSE_MY_NOTICE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.RESPONSE_MY_NOTICE;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.RESPONSE_MY_NOTICE (
	RESPONSE_MY_NOTICE_ID int IDENTITY(1,1) NOT NULL,
	MY_NOTICE_ID int NOT NULL,
	USER_ID int NOT NULL,
	RESPONSE_TEXT nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ATTACHMENT_ID int NULL,
	CREATE_DATE datetime2 DEFAULT getutcdate() NOT NULL,
	COMPANY_ID int NULL,
	CONSTRAINT PK_RESPONSE_MY_NOTICE PRIMARY KEY (RESPONSE_MY_NOTICE_ID),
	CONSTRAINT FK_RESPONSE_MY_NOTICE_ATTACH FOREIGN KEY (ATTACHMENT_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.ATTACHMENTS(ATTACHMENT_ID),
	CONSTRAINT FK_RESPONSE_MY_NOTICE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.COMPANY(COMPANY_ID),
	CONSTRAINT FK_RESPONSE_MY_NOTICE_NOTICE FOREIGN KEY (MY_NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.MY_NOTICES(NOTICE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_RESPONSE_MY_NOTICE_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_RESPONSE_NOTICE_ID ON GUARDIAN-DEV.GUARDIAN.RESPONSE_MY_NOTICE (  MY_NOTICE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.ROLE_FORM_ALLOWLIST definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ROLE_FORM_ALLOWLIST;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ROLE_FORM_ALLOWLIST (
	ROLE_FORM_ALLOWLIST_ID bigint IDENTITY(1,1) NOT NULL,
	ROLE_ID int NOT NULL,
	FORM_ID int NOT NULL,
	[GRANTED] bit NOT NULL,
	COMPANY_ID int NULL,
	CREATE_DATE datetime2 DEFAULT sysutcdatetime() NOT NULL,
	UPDATE_DATE datetime2 NULL,
	UPDATE_USER_ID int NULL,
	CONSTRAINT PK__ROLE_FOR__9DEE4DB39FD24F4B PRIMARY KEY (ROLE_FORM_ALLOWLIST_ID),
	CONSTRAINT FK_RFA_FORM FOREIGN KEY (FORM_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.FORMS(FORM_ID),
	CONSTRAINT FK_RFA_ROLE FOREIGN KEY (ROLE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.ROLES(ROLE_ID)
);
 CREATE UNIQUE NONCLUSTERED INDEX UX_RFA_ROLE_FORM_COMPANY ON GUARDIAN-DEV.GUARDIAN.ROLE_FORM_ALLOWLIST (  ROLE_ID ASC  , FORM_ID ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.ROLE_NOTICE_TYPE_ALLOWLIST definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ROLE_NOTICE_TYPE_ALLOWLIST;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ROLE_NOTICE_TYPE_ALLOWLIST (
	ROLE_NOTICE_TYPE_ALLOWLIST_ID bigint IDENTITY(1,1) NOT NULL,
	ROLE_ID int NOT NULL,
	NOTICE_TYPE varchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[GRANTED] bit NOT NULL,
	COMPANY_ID int NULL,
	CREATE_DATE datetime2 DEFAULT sysutcdatetime() NOT NULL,
	UPDATE_DATE datetime2 NULL,
	UPDATE_USER_ID int NULL,
	CONSTRAINT PK__ROLE_NOT__3AB72B5757542161 PRIMARY KEY (ROLE_NOTICE_TYPE_ALLOWLIST_ID),
	CONSTRAINT FK_RNTA_ROLE FOREIGN KEY (ROLE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.ROLES(ROLE_ID)
);
 CREATE UNIQUE NONCLUSTERED INDEX UX_RNTA_ROLE_TYPE_COMPANY ON GUARDIAN-DEV.GUARDIAN.ROLE_NOTICE_TYPE_ALLOWLIST (  ROLE_ID ASC  , NOTICE_TYPE ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.ROLE_PERMISSIONS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.ROLE_PERMISSIONS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.ROLE_PERMISSIONS (
	ROLE_PERMISSION_ID bigint IDENTITY(1,1) NOT NULL,
	ROLE_ID int NOT NULL,
	PERMISSION_KEY varchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[GRANTED] bit NOT NULL,
	COMPANY_ID int NULL,
	CREATE_DATE datetime2 DEFAULT sysutcdatetime() NOT NULL,
	UPDATE_DATE datetime2 NULL,
	UPDATE_USER_ID int NULL,
	CONSTRAINT PK__ROLE_PER__94A8CC29E65CECE0 PRIMARY KEY (ROLE_PERMISSION_ID),
	CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.ROLES(ROLE_ID)
);
 CREATE UNIQUE NONCLUSTERED INDEX UX_RP_ROLE_KEY_COMPANY ON GUARDIAN-DEV.GUARDIAN.ROLE_PERMISSIONS (  ROLE_ID ASC  , PERMISSION_KEY ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.SUBPOENA_RIDERS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.SUBPOENA_RIDERS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.SUBPOENA_RIDERS (
	RIDER_ID int IDENTITY(1,1) NOT NULL,
	LANGUAGE_TEMPLATE_ID int NOT NULL,
	FRAUD_TYPE nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	POPULATED_LANGUAGE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TOKEN_VALUES_JSON nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	INCIDENT_NOTICE_ID int NULL,
	CREATED_BY int NOT NULL,
	COMPANY_ID int NOT NULL,
	CREATED_AT datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_SUBPOENA_RIDERS PRIMARY KEY (RIDER_ID),
	CONSTRAINT FK_SR_LANG_TEMPLATE FOREIGN KEY (LANGUAGE_TEMPLATE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.SUBPOENA_LANGUAGE_TEMPLATES(LANGUAGE_TEMPLATE_ID),
	CONSTRAINT FK_SR_NOTICE FOREIGN KEY (INCIDENT_NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.MY_NOTICES(NOTICE_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.USER_WORKSPACES definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.USER_WORKSPACES;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.USER_WORKSPACES (
	USER_WORKSPACE_ID int IDENTITY(1,1) NOT NULL,
	USER_ID int NOT NULL,
	WORKSPACE_ID int NOT NULL,
	IS_ACTIVE bit DEFAULT 1 NOT NULL,
	IS_DEFAULT bit DEFAULT 0 NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT getdate() NOT NULL,
	CONSTRAINT PK__USER_WOR__2705AE59CC180FF1 PRIMARY KEY (USER_WORKSPACE_ID),
	CONSTRAINT UQ_USER_WORKSPACES_USER_WORKSPACE UNIQUE (USER_ID,WORKSPACE_ID),
	CONSTRAINT FK_USER_WORKSPACES_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID),
	CONSTRAINT FK_USER_WORKSPACES_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.WORKSPACES(WORKSPACE_ID)
);
 CREATE NONCLUSTERED INDEX IX_USER_WORKSPACES_USER_ACTIVE ON GUARDIAN-DEV.GUARDIAN.USER_WORKSPACES (  USER_ID ASC  , IS_ACTIVE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_USER_WORKSPACES_WORKSPACE_ACTIVE ON GUARDIAN-DEV.GUARDIAN.USER_WORKSPACES (  WORKSPACE_ID ASC  , IS_ACTIVE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.WORK_PROGRESS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.WORK_PROGRESS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.WORK_PROGRESS (
	WORK_PROGRESS_ID int IDENTITY(1,1) NOT NULL,
	REQUEST_ID int NOT NULL,
	USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	PROGRESS_TYPE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'note' NOT NULL,
	TITLE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DESCRIPTION varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HOURS_WORKED decimal(5,2) NULL,
	STATUS_UPDATE varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RELATED_ATTACHMENT_ID int NULL,
	IS_MILESTONE bit DEFAULT 0 NOT NULL,
	IS_VISIBLE_TO_REQUESTOR bit DEFAULT 1 NOT NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	IS_SYSTEM_GENERATED bit DEFAULT 0 NOT NULL,
	RELATED_TASK_ID int NULL,
	STATUS_FROM varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS_TO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EVENT_DATA varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__WORK_PRO__4BF374F2786C964C PRIMARY KEY (WORK_PROGRESS_ID),
	CONSTRAINT FK_WORK_PROGRESS_ATTACHMENT FOREIGN KEY (RELATED_ATTACHMENT_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.ATTACHMENTS(ATTACHMENT_ID),
	CONSTRAINT FK_WORK_PROGRESS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.REQUESTS(REQUEST_ID),
	CONSTRAINT FK_WORK_PROGRESS_USER FOREIGN KEY (USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_COMPANY_ID ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_CREATE_DATE ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  CREATE_DATE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_IS_MILESTONE ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  IS_MILESTONE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_PROGRESS_TYPE ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  PROGRESS_TYPE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_REQUEST_COMPANY ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  REQUEST_ID ASC  , COMPANY_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_REQUEST_ID ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  REQUEST_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_WORK_PROGRESS_USER_ID ON GUARDIAN-DEV.GUARDIAN.WORK_PROGRESS (  USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.EXTERNAL_CALL_REQUESTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.EXTERNAL_CALL_REQUESTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.EXTERNAL_CALL_REQUESTS (
	CALL_REQUEST_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	EXTERNAL_USER_ID int NOT NULL,
	PROPOSED_TIMES nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	MEETING_LINK nvarchar(1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATED_AT datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_EXTERNAL_CALL_REQUESTS PRIMARY KEY (CALL_REQUEST_ID),
	CONSTRAINT FK_ECR_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.MY_NOTICES(NOTICE_ID),
	CONSTRAINT FK_ECR_USER FOREIGN KEY (EXTERNAL_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);


-- [GUARDIAN-DEV].GUARDIAN.EXTERNAL_NOTICE_ASSIGNMENTS definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.EXTERNAL_NOTICE_ASSIGNMENTS;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.EXTERNAL_NOTICE_ASSIGNMENTS (
	ASSIGNMENT_ID int IDENTITY(1,1) NOT NULL,
	NOTICE_ID int NOT NULL,
	EXTERNAL_USER_ID int NOT NULL,
	COMPANY_ID int NOT NULL,
	AGENCY_NAME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CREATED_AT datetime2 DEFAULT getutcdate() NOT NULL,
	CONSTRAINT PK_EXTERNAL_NOTICE_ASSIGNMENTS PRIMARY KEY (ASSIGNMENT_ID),
	CONSTRAINT UQ_ENA_NOTICE_USER UNIQUE (NOTICE_ID,EXTERNAL_USER_ID),
	CONSTRAINT FK_ENA_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.MY_NOTICES(NOTICE_ID),
	CONSTRAINT FK_ENA_USER FOREIGN KEY (EXTERNAL_USER_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.USERS(USER_ID)
);
 CREATE NONCLUSTERED INDEX IX_ENA_COMPANY_EXTERNAL_USER ON GUARDIAN-DEV.GUARDIAN.EXTERNAL_NOTICE_ASSIGNMENTS (  COMPANY_ID ASC  , EXTERNAL_USER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE definition

-- Drop table

-- DROP TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE;

CREATE TABLE [GUARDIAN-DEV].GUARDIAN.FORMS_INSTANCE (
	FORM_INSTANCE_ID int IDENTITY(1000,1) NOT NULL,
	FORM_ID int NOT NULL,
	ASSIGNED_ID int NULL,
	SUBMITTED_DATE datetime NULL,
	CREATE_USER_ID int NULL,
	UPDATE_USER_ID int NULL,
	CREATE_DATE datetime DEFAULT getdate() NOT NULL,
	UPDATE_DATE datetime DEFAULT getdate() NOT NULL,
	COMPANY_ID numeric(38,0) NULL,
	REQUEST_ID int NULL,
	CONSTRAINT PK_FORMS_INSTANCE PRIMARY KEY (FORM_INSTANCE_ID),
	CONSTRAINT FK_FORMS_INSTANCE_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES [GUARDIAN-DEV].GUARDIAN.REQUESTS(REQUEST_ID)
);